### ISSUE TITLE
CAA Support

### ISSUE THREAD

**Issue by laszlof** [github/octodns#104]
I see you have support for CAA in master. Is there any chance we can get a timeframe on a tagged release? We have some things that are depending on it and want to see when we can rollout CAA records in our infrastructure. 

Thanks

**Comment by ross** [comment]
Needed to wrap up https://github.com/github/octodns/pull/105 first. Now that's in place I can go ahead and cut a release.

**Comment by laszlof** [comment]
Nice. Thanks @ross

**Comment by ross** [comment]
Hiccup getting it into pypi, but it's there now.
