### ISSUE TITLE
octodns-sync fails when TXT field "too long"

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#110]
Following the instructions on how to input longer then 255 character TXT fields in Dyn, octodns-sync will fail to sync the multi-segmented TXT records correctly between providers to route53. When I tested the multi-segmented TXT sync from configuration to route53, it also fails.

Both providers require the multi-segmented TXT to be quoted segments without spaces between each segment.

The use of the multi-segment TXT records is for greater then 2048k DKIM records, which are becoming more commonly required.

**Comment by ross** [comment]
Hi @brianeclow this is actually a problem one of my coworkers @antonio ran into a couple weeks ago. It's an oversight in the implementation, something I didn't even know was possible and thus didn't allow for/implement a solution to. It'll take a bit of digging and thinking to come up with an appropriate solution to. I think that octoDNS should be able determine when a record needs to be broken up into multiple segments automatically and do the right thing with the provider, but haven't yet been able to implement that and verify for sure.

**Comment by antonio** [comment]
> this is actually a problem one of my coworkers @antonio ran into a couple weeks ago

My bad, I have been meaning to open this issue for a while but couldn't find the time. Thanks for raising this issue @brianeclow !

**Comment by ross** [comment]
PR with WIP fix for this is https://github.com/github/octodns/pull/115

**Comment by brianeclow** [comment]
Awesome. Thank you on the quick turn around. Do you have an idea when you will be cutting the next version with this patch?

**Comment by ross** [comment]
> Awesome. Thank you on the quick turn around. Do you have an idea when you will be cutting the next version with this patch?

I'll probably hold off until the [google cloud provider](https://github.com/github/octodns/pull/113) has landed to avoid doing 2 quick releases. In the meantime a pip/requirements.txt line like the following should grab it:

```
-e git+ssh://git@github.com/github/octodns.git@e0f357d9f9c041238b069b5fc4c1f4c663bf16a8#egg=octodns
```

**Comment by blakestoddard** [comment]
Did this break? I've got a DKIM record that is >255 characters and octodns `0.9.6` returns this with an unchunked value at the end:
```
2019-09-17T17:40:15  [140441762571072] INFO  Route53Provider[route53] _apply:   sending change request for batch of 1 mods, 1 ResourceRecords
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-sync')()
  File "/src/octodns/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/src/octodns/octodns/manager.py", line 313, in sync
    total_changes += target.apply(plan)
  File "/src/octodns/octodns/provider/base.py", line 143, in apply
    self._apply(plan)
  File "/src/octodns/octodns/provider/route53.py", line 745, in _apply
    self._really_apply(batch, zone_id)
  File "/src/octodns/octodns/provider/route53.py", line 756, in _really_apply
    HostedZoneId=zone_id, ChangeBatch=batch)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Invalid Resource Record: FATAL problem: CharacterStringTooLong (Value is too long) encountered with '"v=DKIM1\; k=rsa\; p=MIIB...
```

The config file looks like this:
```
mail._domainkey:
  ttl: 120
  type: TXT
  values: 
  - v=DKIM1\; k=rsa\; p=MIIB...<record is 417 characters>
```
