### ISSUE TITLE
OvhProvider: Support for DKIM record

### ISSUE THREAD

**Issue by webs86** [github/octodns#114]
Ovh translate in his system TXT record with DKIM key with a dedicated record named DKIM and not TXT (if I check dns record via dig I view correct TXT record, but via API it is an DKIM record).

When I use `octodns-dump` to create YAML config file it fail because it does not find `_data_for_DKIM`

This is traceback:
~~~
Traceback (most recent call last):
  File "/home/webs86/Documenti/gitlab/samuelez/dns/env/bin/octodns-dump", line 9, in <module>
    load_entry_point('octodns==0.8.6', 'console_scripts', 'octodns-dump')()
  File "/home/webs86/Documenti/gitlab/samuelez/dns/env/local/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/home/webs86/Documenti/gitlab/samuelez/dns/env/local/lib/python2.7/site-packages/octodns/manager.py", line 362, in dump
    source.populate(zone, lenient=lenient)
  File "/home/webs86/Documenti/gitlab/samuelez/dns/env/local/lib/python2.7/site-packages/octodns/provider/ovh.py", line 65, in populate
    data_for = getattr(self, '_data_for_{}'.format(_type))
AttributeError: 'OvhProvider' object has no attribute '_data_for_DKIM'
~~~

**Comment by ross** [comment]
Interesting. If you set up a TXT record with the DKIM info it in with OVH does everything work correctly? If so the cleanest path may be to add a `_data_for_DKIM` and have that return an appropriate TXT record. That could run in to interesting problems during the sync/apply so would need some checking and testing.

/cc @trnsnt as the author of the OVH provider

**Comment by trnsnt** [comment]
Hello,
Sorry for the delay, I will look at it this week. It seems that adding _data_for_DKIM is a good solution.

**Comment by webs86** [comment]
Hi @trnsnt ,
I have tried to implement it, but I have some problems with tests. You can view on my fork on ovh-dkim-record.

Thank you

**Comment by ross** [comment]
> I have tried to implement it, but I have some problems with tests. You can view on my fork on ovh-dkim-record.

@webs86 took a quick look at your branch. Since `DKIM` is a specific use of TXT and not really a distinct record type (outside of OVH I guess) It's probably best to hide the implementation detail from the user. I can think of two ways to go about that:

1. When you encounter a `DKIM` record during populate convert it into a `TXT` to pass to `Record.new`.
   * This assumes that it's possible to create `TXT` records in OVH which have `DKIM` values. 
   * It may convert them to `TXT` records the first time things are synced, but that doesn't seem like a huge deal
1. When you encounter a `DKIM` record during populate conert it into a `TXT` record and do the reverse, converting `TXT` `Record`s that contain DKIM info into `DKIM`
   * Not sure how safe/easy it'd be to do the conversion on the way in

I'd start with the first option if possible and only look at the second if that didn't work out.

**Comment by trnsnt** [comment]
Hi @webs86, @ross 

Sorry for the delay, I was busy previous weeks. This week will be much better :)

Concerning the first solution you proposed, the main drawback is that TXT records are limited to 255 chars, so if DKIM is bigger than this limit, it will not work.

I think second solution is the one to use with OVH provider. 
I am working on it, but main difficulty is about DKIM detection.  

@webs86, I will share a first version of a fork today

**Comment by trnsnt** [comment]
@webs86, here is my branch (still WIP (missing tests, and some rework)) 
https://github.com/trnsnt/octodns/tree/ovh-support-dkim
What do you think of it ?

**Comment by ross** [comment]
> Concerning the first solution you proposed, the main drawback is that TXT records are limited to 255 chars, so if DKIM is bigger than this limit, it will not work.

Is that a limitation of OVH? The 255-max limit issue for octoDNS should have been fixed with the `chunked_value` stuff in #127.

> I think second solution is the one to use with OVH provider.
> I am working on it, but main difficulty is about DKIM detection.

Yeah, that's why it was my second suggestion and not first. Fwiw it should be fine to test your detection function directly with calls to `OvhProvider._is_dkim`.

**Comment by trnsnt** [comment]
Yes limitation is on OVH side. Unfortunately, TXT records are truncated if they are longer than 255 chars.
I agree with you, about testing OvhProvider._is_dkim, it will be easier like that. I Will do it tomorrow

**Comment by yzguy** [comment]
DKIM Record support added in #135, this issue can probably be closed.
