### ISSUE TITLE
DYN: Traffic director services not found.

### ISSUE THREAD

**Issue by timhughes** [github/octodns#126]
It appears that other people have a ':' in the label that is returned from DYN. I dont think necessarily always true. Acording to the docs it is a "string" "Name of the Traffic Director service." https://help.dyn.com/update-dsf-api/ 

This is the example response i think the tests are using.  
https://github.com/github/octodns/blob/7f2c292f5ac5f99808c843f68dcb47c7ed4dccf7/tests/fixtures/dyn-traffic-director-get.json#L4179

If i modify the code at: 
https://github.com/github/octodns/blob/7f2c292f5ac5f99808c843f68dcb47c7ed4dccf7/octodns/provider/dyn.py#L292

to be like  
```
            for td in get_all_dsf_services():
                print(td)
                try:
                    print(td.label)
                    fqdn, _type = td.label.split(':', 1)
                except ValueError as e:
                    print("Ahhhhhh: %s" % e)
                    continue
```

Then the output i get when trying to octodns-dump the domain I get

<TrafficDirector>: website-production, ID: XXXX-XXXXXXXXXXXXXXXXX
website-production
Ahhhhhh: need more than 1 value to unpack
<TrafficDirector>: asia-trader, ID: YYYY-YYYYYYYYYYYYYYYY
asia-trader
Ahhhhhh: need more than 1 value to unpack

**Comment by ross** [comment]
> "label": "unit.tests.:A"

This is the format that octoDNS uses for TD records that it creates. If there are existing TD/geo records that don't match this format (I wouldn't expect anyone's records to match) octoDNS won't be able to import them cleanly. 

There's not really an existing fully supported process for importing a setup with advanced records. I mulled over trying to do something like that early on, but decided that there was so much possible variation in the way that Dyn allows things to be set up that the chance of it fulling working were slim. Especially the case since I don't have examples to work from.

If the dump process is throwing errors then it's definitely something I'd like to avoid. The end result would probably be to print or error out with a clear warning about what's going on. 

I don't have a complete/good story on what importing such zones would look like. It'd probably involve getting a dump of all of the standard records and then manually recreating the advanced stuff. That would result in most things being left untouched, but would still recreate the TD records using octoDNS's setup. I know it's not a great story, but I don't have any leads on a better one at the moment.

**Comment by timhughes** [comment]
When I build a minimal script that replicates the call I get this.

```python
import os
from pprint import pprint
from dyn.tm.session import DynectSession
from dyn.tm.zones import Zone
from dyn.tm.services.dsf import get_all_dsf_services

dynect_session = DynectSession(os.environ['DYN_CUSTOMER'], os.environ['DYN_USERNAME'], os.environ['DYN_PASSWORD'])
result = get_all_dsf_services()
for td in result:
    for k, v in td.__dict__.items():
        print "k:{}, v:{}".format(k, v)
```

```
hughest@argon [0] $ python test.py
------------------------
k:_label, v:website-production
k:_note, v:None
k:_pending_change, v:
k:_ttl, v:30
k:_publish, v:None
k:_active, v:Y
k:uri, v:/DSF/XXXX-XXXXXXXXXXXXXXXX/
k:_service_id, v:XXXX-XXXXXXXXXXXXXXXX
k:_nodes, v:[]
k:_rulesets, v:[]
k:_response_pools, v:None
k:_record_sets, v:None
k:_notifiers, v:[]
k:_implicitPublish, v:True
------------------------
k:_label, v:asia-trader
k:_note, v:None
k:_pending_change, v:
k:_ttl, v:3600
k:_publish, v:None
k:_active, v:Y
k:uri, v:/DSF/YYYY-YYYYYYYYYYYYYYYYY/
k:_service_id, v:YYYY-YYYYYYYYYYYYYYYYY
k:_nodes, v:[]
k:_rulesets, v:[]
k:_response_pools, v:None
k:_record_sets, v:None
k:_notifiers, v:[]
k:_implicitPublish, v:True
```

**Comment by timhughes** [comment]
That was a quick response :-)

So I gather from what you have said , i need to call the traffic dorector the zone name followed by the type of record that is being managed ? eg. example.com.:CNAME or foo.bar.:A

**Comment by timhughes** [comment]
I am happy to make a PR for this to be added into the docs at https://github.com/github/octodns/blob/master/docs/records.md Are there any other "opinionated views" that should be added in there.

**Comment by ross** [comment]
> So I gather from what you have said , I need to make the traffic director label equal to the zone name followed by the type of record that is being managed ?

If things otherwise use the same structure as octoDNS that would may sufficient. To be honest I'd have to debug/look at the specific case in detail to know for sure. There was a lot of "design" time spent to try and make sure that the setup in Dyn matched what could be done with Route53 and more generally could (hopefully) be abstracted to other providers. It's quickly likely not the sort of setup that would be created by hand by someone just using Dyn. Sorry this is so complicated, but in my defense the Dyn TD stuff isn't exactly simple :grin:

> It also maye be worth adding a warning at
> 
> octodns/octodns/provider/dyn.py
> Line 294 in 7f2c292
>  continue

Definitely.

**Comment by timhughes** [comment]
I think I am getting the hang of this now but I am stuck. 

When loading the rule sets they expect their label to be in this format again with the ":" as a seperator 

"NA-US-CA:b2c71ae53a5645cc813c51db2b6571c7",
"NA-US:b2c71ae53a5645cc813c51db2b6571c7",
"AS-JP:b2c71ae53a5645cc813c51db2b6571c7",
"AF:b2c71ae53a5645cc813c51db2b6571c7",
"default:b2c71ae53a5645cc813c51db2b6571c7",


Does the part opon the right hand side corrospond with something else somewhere or is it just a uniq identifier 

https://help.dyn.com/managing-rule-sets/#definition

Also , is this an appropriate place to be asking these questions or would you prefer some other medium?

**Comment by ross** [comment]
> Does the part opon the right hand side corrospond with something else somewhere or is it just a uniq identifier

Unique identifier. Dyn didn't like having multiple rules with the same label so I had to fudge them. 

> Also , is this an appropriate place to be asking these questions or would you prefer some other medium?

This is good. At this point the volume isn't high enough for a mailing list or irc/slack to pay off :-)

**Comment by timhughes** [comment]
I believe I have finally worked this out.  Does the following make sense? If so then I will raise a PR and get it added to the docs.  

---
From the following example we have a geo tag with three entries NA-US-CA, NA-US-NY, OC-AU. Octodns creates another one labeled 'default' with the details for the actual A record.

```yaml
---
? ''
: type: TXT
  value: v=spf1 -all
test:
  geo:
    NA-US-NY:
    - 111.111.111.1
    NA-US-CA:
    - 111.111.111.2
    OC-AU:
    - 111.111.111.3
    EU
    - 111.111.111.4
  ttl: 300
  type: A
  value: 111.111.111.5
```


The geo labels breakdown based on:

1. 'AF': 14,  # Continental Africa
    'AN': 17,  # Continental Antartica
    'AS': 15,  # Contentinal Asia
    'EU': 13,  # Contentinal Europe
    'NA': 11,  # Continental North America
    'OC': 16,  # Contentinal Austrailia/Oceania
    'SA': 12,  # Continental South America

2. ISO Country Code https://en.wikipedia.org/wiki/ISO_3166-2

3. ISO Country Code Subdevision as per https://en.wikipedia.org/wiki/ISO_3166-2:US   (change the code at the end for the country you are subdividing) * these may not always be supported.

So the example is saying:

- North America - United States - New York:  gets served an "A" record of  111.111.111.1
- North America - United States - California:   gets served an "A" record of  111.111.111.2
- Oceania - Australia: Gets served an "A" record of 111.111.111.3
- Europe: gets an "A" record of 111.111.111.4
- Everyone else gets an "A" record of 111.111.111.5


Octodns will automatically set up a monitor and check for **https://<ip_address>/_dns** and check for a 200 response. 


-----------------------------------------
On a side note is there any kind of macros you can use to insert bits of yaml. For example I want the same geo layout across several domains. Using the example above is there abything that can do something like this.

```yaml
---
? ''
: type: TXT
  value: v=spf1 -all
test:
  geo: lookup("geo_array")
  ttl: 300
  type: A
  value: 111.111.111.5
```

An example of this is hiera from puppetlabs https://puppet.com/docs/puppet/5.3/hiera_interpolation.html

**Comment by ross** [comment]
> ...

👍 everything looks correct.

> Octodns will automatically set up a monitor and check for https://<ip_address>/_dns and check for a 200 response.

Yeah. The details of the check implementation depends on the provider, Dyn vs Route53. I've tried to make them as close as possible in behavior, but there are diffs. The main one that I know of is that Dyn will check each IP address when there are multiple values, but Route53 only checks the first value of each list. 

> On a side note is there any kind of macros you can use to insert bits of yaml. For example I want the same geo layout across several domains. Using the example above is there abything that can do something like this.

There is not currently, though depending on how fully featured PyYAML is there may be some yaml specific tricks you can do (I've not tried.) #7 was created to discuss and track this specific functionality, but hasn't been something that's made it to the top of the todo list.

> If so then I will raise a PR and get it added to the docs.

That would be awesome. octoDNS could use a lot of documentation love, I've not had enough time/motivation to spend on it on top of "keeping the lights on" so I'd welcome others to do so. You definitely seem to have dug into the geo stuff enough to understand it. The only bit I'd suggest adding on top of the example is to indicate clearly that the geo values are arrays by having one or more of them with multiple values.
