### ISSUE TITLE
NS1: Single Value Records with no answer raises IndexError

### ISSUE THREAD

**Issue by yzguy** [github/octodns#131]
So just dumping our zone, got this error. We had a PTR record in our forward zone in NS1, no idea why, but it also had no answers.

Response from NS1
```
PTR, {u'domain': u'asmith.net', u'short_answers': [], u'link': None, u'ttl': 3600, u'tier': 1, u'type': u'PTR', u'id': u'1b05cd7943dde9d3'}
```

Error
```
Traceback (most recent call last):
  File "/Users/asmith/as-octodns/venv/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/Users/asmith/as-octodns/venv/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/Users/asmith/as-octodns/venv/lib/python2.7/site-packages/octodns/manager.py", line 362, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/asmith/as-octodns/venv/lib/python2.7/site-packages/octodns/provider/ns1.py", line 156, in populate
    record = Record.new(zone, name, data_for(_type, record),
  File "/Users/asmith/as-octodns/venv/lib/python2.7/site-packages/octodns/provider/ns1.py", line 76, in _data_for_CNAME
    'value': record['short_answers'][0],
IndexError: list index out of range
```

The record doesn't make sense, plus why have a record with no answers. I believe this should probably throw a ValidationError with a "No Records" reason.

Also at least for NSOne, it's another convenience, you don't have to put the `.` in, and it will still put it when you query for it.

**Comment by yzguy** [comment]
I'd like to tackle this one, would like some feedback on if it should be a validation error or not, etc.

Thanks

**Comment by ross** [comment]
> I'd like to tackle this one, would like some feedback on if it should be a validation error or not, etc.

That's an interesting one. I don't think it is/should be valid to have a record with no values. I just tried to find a way in a couple other providers to add a "node" without any values and wasn't able to do so.

I think the best thing to do here is probably to handle that case in the NS1Provider's [`_data_for_CNAME`](https://github.com/github/octodns/blob/f39e1d28c810138daa62a86cafdc39492bcad670/octodns/provider/ns1.py#L71-L76). Happy to take a look at that and answer any questions if you run into any bumps in the road. The unit testing for that case will be the more interesting bit. 

This has actually brought up something tangentially related is that I'm not 100% sure of the behavior of Record when it gets an empty `value` or zero-length `values` array. I've added a todo for myself to look into the handling of that. I think the NS1 exception/problem should be tackled separate as its more of a bug in the provider, but it does raise interesting questions 😁 .

**Comment by yzguy** [comment]
So besides being a PTR record in a forward zone, you can't query for it/get an answer, or even an A record

```
-> dig PTR asmith.net @dns1.p07.nsone.net.

; <<>> DiG 9.8.3-P1 <<>> PTR asmith.net @dns1.p07.nsone.net.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65510
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;asmith.net.         IN  PTR

;; AUTHORITY SECTION:
asmith.net.      3600    IN  SOA dns1.p01.nsone.net. hostmaster.nsone.net. 1508539750 43200 7200 1209600 3600

;; Query time: 20 msec
;; SERVER: 198.51.44.7#53(198.51.44.7)
;; WHEN: Fri Oct 20 15:52:10 2017
;; MSG SIZE  rcvd: 102
```

```
-> dig asmith.net @dns1.p07.nsone.net.

; <<>> DiG 9.8.3-P1 <<>> asmith.net @dns1.p07.nsone.net.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9988
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;asmith.net.         IN  A

;; AUTHORITY SECTION:
asmith.net.      3600    IN  SOA dns1.p01.nsone.net. hostmaster.nsone.net. 1508540222 43200 7200 1209600 3600

;; Query time: 12 msec
;; SERVER: 198.51.44.7#53(198.51.44.7)
;; WHEN: Fri Oct 20 15:57:07 2017
;; MSG SIZE  rcvd: 102

```

It also doesn't even show up in zone transfers

**Comment by ross** [comment]
> So besides being a PTR record in a forward zone, you can't query for it/get an answer, or even an A record

:cool: That matches up with it being a ~bug/oversight in NS1's system and agrees with just pretending it doesn't exist. That may be able to be revisited down the road if/when there's clean validation stuff setup for empty values (as mentioned above,) but for now it's the best option.

**Comment by yzguy** [comment]
I'm not sure if there actually needs to be a code change to the NS1 Provider. That no value record wasn't made with OctoDNS, but manually via the UI/API at some point. It only presented an error when I tried to dump it. 

I believe maybe the the dump process should present a normal ValidationError saying "No Values" as a reason, rather than hitting a index out of range error. This would make it apparent to the user that they have a record that is not correct, and they should remove it. It would be the same thing as not having a `.` at the end of a CNAME value, you have to go correct that before OctoDNS will let you dump it.

I simply went and deleted it because it's not even valid, and NS1 clearly won't serve the record. After that I was able to dump the zone correctly.

The bigger question was what would happen if you tried to create a record with no values/empty values, etc. via OctoDNS.

I tested trying to make a record with these tests:

1. No `value` or `values` key

	* Test:

		```
		test:
		  type: A
		```
	
	* Result:

		```
		octodns.record.ValidationError: Invalid record test.yzguy.io.
		  - missing value(s)
		```

2. `value` key, no value

	* Test:

		```
		test:
		  type: A
		  value:
		```

	* Result:
	
		```
		octodns.record.ValidationError: Invalid record test.yzguy.io.
		  - invalid ip address "None"
		```
	
3. `values` key, no values

	* Test:
		
		```
		test:
		  type: A
		  values:
		```
	
	* Result:
		
		```
		TypeError: 'NoneType' object is not iterable
		```

4. `values` key, 1 empty index

	* Test:
		
		```
		test:
		  type: A
		  values:
		    -
		```

	* Result:
		
		```
		octodns.record.ValidationError: Invalid record test.yzguy.io.
		  - invalid ip address "None"
		```

So OctoDNS definitely does the right thing and stops it, except Test 3, which just failed because it tried to iterate on an empty list, so something could probably be done about that to be more user friendly.

I'm cool with closing this issue, and opening another that deals with the ValidationError due to no values on a dump.

I'm confident enough that OctoDNS currently won't allow you to create a DNS record on any provider if you don't specify any values, and the clean validation stuff will address the friendliness of the errors, etc.

**Comment by ross** [comment]
> I believe maybe the the dump process should present a normal ValidationError saying "No Values" as a reason, rather than hitting a index out of range error

I agree with that.

> 3 values key, no values
> 
> Test:
> 
>  test:
>    type: A
>    values:
> Result:
> 
>  TypeError: 'NoneType' object is not iterable

Yeah this is the main case that would need to be dealt with as you discovered the other situations are reasonably handled. 

The one potential wrinkle is making sure the `lenient` mode behavior (the stuff used when dumping) is to warn and allow the "bad" value through with an appropriate message. Then things will complain and fail if you were to try and push them. That was the behavior introduced in #8 

> I'm cool with closing this issue, and opening another that deals with the ValidationError due to no values on a dump.

Up to you. It's fine to track it here since there's already relevant discussion. You could update the time to reflect the change if that makes sense to you.

**Comment by yzguy** [comment]
All sounds good. I'm working on the change

I have it "working", just need to fix up the tests/new ones

If you dump it without lenient you get

```
octodns.record.ValidationError: Invalid record test.yzguy.io.
  - missing value(s)
```

If you specify `--lenient` it will complete, giving the warning

```
2017-10-22T20:46:43  [140737049330624] WARNING Record Invalid record test.yzguy.io.
  - missing value(s)
```

and you're YAML file will look like this

```
test:
  type: A
```

Which would be caught if you applied it with a 

```
 octodns.record.ValidationError: Invalid record test.yzguy.io.
   - missing value(s)
```

**Comment by yzguy** [comment]
After the new code, ran the tests and got

```
======================================================================
ERROR: test_populate (test_octodns_provider_dnsimple.TestDnsimpleProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yzguy/Projects/foss/octodns/tests/test_octodns_provider_dnsimple.py", line 99, in test_populate
    provider.populate(zone)
  File "/Users/yzguy/Projects/foss/octodns/octodns/provider/dnsimple.py", line 272, in populate
    source=self, lenient=lenient)
  File "/Users/yzguy/Projects/foss/octodns/octodns/record.py", line 102, in new
    raise ValidationError(fqdn, reasons)
ValidationError: Invalid record unit.tests.
  - missing value(s)
```

I'm thinking that the test that failed is not needed anymore, as it's invalidated at the "record" level, versus at a specific provider.

If so, I believe it would be removing Lines 89 - 116 in `tests/test_octodns_provider_dnsimple.py`, as well as deleting `tests/fixtures/dnsimple-invalid-content.json`, let me know if that's correct. I don't want to remove the `bust the cache` part if that's necessary.

**Comment by yzguy** [comment]
Made a PR here: https://github.com/github/octodns/pull/132

**Comment by yzguy** [comment]
So after some poking around. I now realize/understand the change that would need to happen in the NS1 Provider.

Originally I had a PTR record with no answers, which is the same method for CNAME and ALIAS

So before even getting to the `validate` method of octodns/record.py in`ValueMixin`, it's failing with my original error

```
Traceback (most recent call last):
  File "/Users/yzguy/Projects/yzguy-octodns/venv/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/Users/yzguy/Projects/yzguy-octodns/venv/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/Users/yzguy/Projects/yzguy-octodns/venv/lib/python2.7/site-packages/octodns/manager.py", line 362, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/yzguy/Projects/yzguy-octodns/venv/lib/python2.7/site-packages/octodns/provider/ns1.py", line 155, in populate
    record = Record.new(zone, name, data_for(_type, record),
  File "/Users/yzguy/Projects/yzguy-octodns/venv/lib/python2.7/site-packages/octodns/provider/ns1.py", line 75, in _data_for_CNAME
    'value': record['short_answers'][0],
IndexError: list index out of range
```

So at least for NS1, when dumping/nooping it will give the error above if you have a CNAME, ALIAS, or PTR with no answers

Something like

```
    def _data_for_CNAME(self, _type, record):
        if len(record['short_answers']) == 0:
            value = None # First option, produces null in zone file
            value = ''       # Second option, produces '' in zone file
        else:
            value = record['short_answers'][0]

        return {
            'ttl': record['ttl'],
            'type': _type,
            'value': value,
        }
```

The above code will produce a sane default, triggering the other validations that checks for None or zero-length.

**Comment by yzguy** [comment]
First PR here to handle the issues in NS1 Provider: https://github.com/github/octodns/pull/136

That PR will help fix up NS1 to work correctly with the validations.

**Comment by yzguy** [comment]
2nd part of issue fixed in: https://github.com/github/octodns/pull/132

Closing.
