### ISSUE TITLE
NS and SOA records

### ISSUE THREAD

**Issue by oryagel** [github/octodns#149]
Hi,
General question, but especially relevant to OctoDNS users.

Should I match the NS and SOA records between the different providers we use?
Should I create the records in the YAML file and then sync them back to both providers or maybe these records can be ignored and we just need to add the DNS servers from both providers to the registrar?

Thanks

**Comment by yzguy** [comment]
These are relevant issues:
https://github.com/github/octodns/issues/38
https://github.com/github/octodns/issues/39

I'd say having them in sync is a good idea, so you don't have differences between providers. However there are definitely differences between providers in their features, eg. Dyn you cannot remove their nameservers, but you can add some. Some providers do not allow you to change the SOA, eg DigitalOcean

The one SOA option I have seen that you cannot usually control is the Serial, so those would definitely be out of sync, but that's only really relevant to secondaries. If you're using OctoDNS you probably aren't using secondaries though.

If you're doing multi-provider, you would have your name servers from both providers in the registar, and configured in the providers, you would want both name servers, eg. Dyn in NS1, and NS1 in Dyn.

**Comment by ross** [comment]
There are 2 WIP PRs (that have were created long ago) for SOA, https://github.com/github/octodns/pull/45,  and NS, https://github.com/github/octodns/pull/53, record management. The SOA one probably isn't going anywhere. I ran into too many problems with providers support of managing them and couldn't really come up with a cohesive plan for them. 

The NS record PR can probably ship with a bit of updating and care, though it's a VERY sensitive change and the behaviors of providers there are less than idea, some will let you add more NS records, but not remove their own etc. That usually isn't an issue, but could result in situations where the resulting values don't match what's configured.

**Comment by oryagel** [comment]
Thanks!

I reviewed the issues you mentioned, but I still don't understand what the recommended configuration.
Currently we have a single provider. I was inspired by the post in the engineering blog and want to add a secondary provider and "DNS as code". We don't have secondaries, meaning that all the records for a specific domain are managed by the same provider. 
If it helps, I don't mind updating a few NS records manually. I'm not sure what you recommend regarding NS and SOA records and would appreciate clarification.

**Comment by ross** [comment]
If you have multiple providers configured to serve your records it is best to have all of the name servers include in both the registrar and zone ROOT NS records.

github.com's registrar records:

```
otter:~ ross$ dig NS github.com. @ns1.p16.dynect.net.

; <<>> DiG 9.8.3-P1 <<>> NS github.com. @ns1.p16.dynect.net.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30944
;; flags: qr aa rd; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;github.com.			IN	NS

;; ANSWER SECTION:
github.com.		900	IN	NS	ns-421.awsdns-52.com.
github.com.		900	IN	NS	ns3.p16.dynect.net.
github.com.		900	IN	NS	ns4.p16.dynect.net.
github.com.		900	IN	NS	ns1.p16.dynect.net.
github.com.		900	IN	NS	ns-1283.awsdns-32.org.
github.com.		900	IN	NS	ns-1707.awsdns-21.co.uk.
github.com.		900	IN	NS	ns-520.awsdns-01.net.
github.com.		900	IN	NS	ns2.p16.dynect.net.

;; Query time: 21 msec
;; SERVER: 208.78.70.16#53(208.78.70.16)
;; WHEN: Tue Nov 14 13:29:12 2017
;; MSG SIZE  rcvd: 248
```

And our ROOT NS has all 8 as well

```
otter:~ ross$ dig NS github.com. @ns1.p16.dynect.net.

; <<>> DiG 9.8.3-P1 <<>> NS github.com. @ns1.p16.dynect.net.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30944
;; flags: qr aa rd; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;github.com.			IN	NS

;; ANSWER SECTION:
github.com.		900	IN	NS	ns-421.awsdns-52.com.
github.com.		900	IN	NS	ns3.p16.dynect.net.
github.com.		900	IN	NS	ns4.p16.dynect.net.
github.com.		900	IN	NS	ns1.p16.dynect.net.
github.com.		900	IN	NS	ns-1283.awsdns-32.org.
github.com.		900	IN	NS	ns-1707.awsdns-21.co.uk.
github.com.		900	IN	NS	ns-520.awsdns-01.net.
github.com.		900	IN	NS	ns2.p16.dynect.net.

;; Query time: 21 msec
;; SERVER: 208.78.70.16#53(208.78.70.16)
;; WHEN: Tue Nov 14 13:29:12 2017
;; MSG SIZE  rcvd: 248
```

octoDNS doesn't support editing either location (currently) so they will need to be hand managed as you mention. 

It was recommended to us to include all name severs in both locations. We don't have anything concrete/presentable (I hope that will change at some point) but in lightweight testing we've found that some DNS resolvers do look to and use/prefer the ROOT NS records for a zone. It's not absolutely required, but it seems to be a good idea.

There was a talk at Velocity NYC by @lexelby that might be of interest as well: https://www.youtube.com/watch?v=Y1frKCKL8xA

**Comment by yzguy** [comment]
I think you had a copy + pasta error :)

Registrar:

```
-> whois github.com | grep -e "^Name Server"
Name Server: ns-520.awsdns-01.net
Name Server: ns-1707.awsdns-21.co.uk
Name Server: ns1.p16.dynect.net
Name Server: ns3.p16.dynect.net
Name Server: ns-1283.awsdns-32.org
Name Server: ns-421.awsdns-52.com
Name Server: ns2.p16.dynect.net
Name Server: ns4.p16.dynect.net
```

com. nameservers

```
-> dig NS github @$(dig NS com. +short | tail -n 1)

; <<>> DiG 9.9.7-P3 <<>> NS github @d.gtld-servers.net.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38919
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 13, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.				IN	NS

;; AUTHORITY SECTION:
.			518400	IN	NS	k.root-servers.net.
.			518400	IN	NS	l.root-servers.net.
.			518400	IN	NS	m.root-servers.net.
.			518400	IN	NS	a.root-servers.net.
.			518400	IN	NS	b.root-servers.net.
.			518400	IN	NS	c.root-servers.net.
.			518400	IN	NS	d.root-servers.net.
.			518400	IN	NS	e.root-servers.net.
.			518400	IN	NS	f.root-servers.net.
.			518400	IN	NS	g.root-servers.net.
.			518400	IN	NS	h.root-servers.net.
.			518400	IN	NS	i.root-servers.net.
.			518400	IN	NS	j.root-servers.net.

;; Query time: 40 msec
;; SERVER: 192.31.80.30#53(192.31.80.30)
;; WHEN: Tue Nov 14 20:18:43 PST 2017
;; MSG SIZE  rcvd: 246
```

**Comment by oryagel** [comment]
Thanks. I'll update the NS records in both providers manually and ignore the SOA record.

There are many tools to check the DNS configuration online after the change in the registrar. Can you recommend tools to check the configuration by specifying the name servers before applying the change to the registrar?

**Comment by yzguy** [comment]
Google used to have a decent Dig service, but they removed the ability to specify a nameserver to query.

I'm partial to just using `whois` and `dig`. `nslookup` on windows would be equivalent.

**Comment by oryagel** [comment]
Hi,
I used https://zonemaster.net for the tests. The domain I'm testing is `tccsetup dot com`. I'm getting error which says `The smallest possible legal referral packet is larger than 512 octets (it is 536).` I tried to read about that error but couldn't find anything valuable.
Any idea what the issues is and how to fix that?

Thanks

**Comment by ross** [comment]
> The smallest possible legal referral packet is larger than 512 octets (it is 536).

Not familiar with that. I checked a few other (octoDNS managed split domains) and don't get that error for them. Some quick googling didn't turn up anything for me. You might try contacting the people who own that site and see what they say. Maybe it's just a non-standard error message/warning. No clue if they'd be responsive or not, but might be worth a shot.
