### ISSUE TITLE
Install the last version of octoDNS from master branch

### ISSUE THREAD

**Issue by wmariuss** [github/octodns#157]
After using this command `python -m pip install .` or `python setup.py install` to install the last version of octoDNS (master branch) it gives me:
`Successfully installed UNKNOWN-0.0.0`

**Comment by wmariuss** [comment]
I can see in your bootstrap script you use `pip install -e .[dev,test]`. The same issue.

**Comment by ross** [comment]
I van verify this is the case. It's not particually important in the bootstrap case since you normally aren't using the installed version (ideally it wouldn't install.) 

/cc @4383 who did the setup tools PR in case it's something obvious/easy.

**Comment by wmariuss** [comment]
I updated the message.
`Successfully installed UNKNOWN`

**Comment by 4383** [comment]
You need to update setuptools before run `python setup.py install` or `python -m pip install`

`pip install -U setuptools`

**Comment by wmariuss** [comment]
Ohh, that was easy :) Thank you.
