### ISSUE TITLE
Support Cloudflare Proxying 

### ISSUE THREAD

**Issue by jacobleonw** [github/octodns#158]
Add the ability to enable proxying on Cloudflare records
https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record

**Comment by ross** [comment]
Thanks for reaching out. This has been previously brought up in https://github.com/github/octodns/issues/65 so I'm going to close this one to consolidate things there.

**Comment by begincalendar** [comment]
Given that #182 doesn't allow you to toggle CloudFlare proxying, should this issue be re-opened?
