### ISSUE TITLE
Validation requires trailing dot on wildcard entries

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#159]
Found an interesting edge case when we went to update the wildcard entries on some of our zones. We updated the data yaml files, then attempted to push to multiple providers, and the follow error ensued:

```
Traceback (most recent call last):
  File "dns/env/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-sync')()
  File "dns/env/src/octodns/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "dns/env/src/octodns/octodns/manager.py", line 260, in sync
    plans = [p for f in futures for p in f.result()]
  File "dns/env/src/octodns/octodns/manager.py", line 49, in result
    return self.func(*self.args, **self.kwargs)
  File "dns/env/src/octodns/octodns/manager.py", line 183, in _populate_and_plan
    source.populate(zone)
  File "dns/env/src/octodns/octodns/provider/yaml.py", line 69, in populate
    lenient=lenient)
  File "dns/env/src/octodns/octodns/record.py", line 102, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record *.example.com.
  - missing trailing .
```

Interestingly enough, this does not appear to occur when you "sync" between providers.

**Comment by ross** [comment]
Hi @brianeclow - CNAMEs are required to end with a `.`. some providers force or add it automatically, others don't. octoDNS tries to enforce best practices and the validations require them. Any chance that `*.example.com.` is a `CNAME` and has a value(s) without trailing `.`? If so you should be able to add one on the end of them and everything should work. Lmk if something else is up.

**Comment by brianeclow** [comment]
That makes general sense. Adding more context, we are updating a wildcard value from
```
'*':
  ttl: 300
  type: CNAME
  value: host.example.com.
```
to
```
'*':
  ttl: 300
  type: CNAME
  value: www
```
Which, I just realized, the person putting together the PR, did not use an FQDN with a trailing-dot on the `value`. I thought it was throwing an error about the key. :facepalm:

Alright, thank you for the help.

**Comment by ross** [comment]
:cool: The error message probably could be a bit clearer there... Hadn't occurred to me since I wrote it and when I see it know what it means :-)
