### ISSUE TITLE
Route53: incorrect 'None' value in NAPTR record

### ISSUE THREAD

**Issue by sshmanko** [github/octodns#161]
NAPTR records can have empty value for its 'regexp' field (see https://tools.ietf.org/html/rfc2915#section-7.1)

If such records present in zone, Route53 provider incorrectly reports changes:
```* route53 (Route53Provider)
*   Update
*     <NaptrRecord NAPTR 1800, sip.tnx.test.example.com., [''30 10 "S" "SIPS+D2T" "" _sips._tcp.sip.tnx.example.com.'']> ->
*     <NaptrRecord NAPTR 1800, sip.tnx.test.example.com., [''30 10 "S" "SIPS+D2T" "" _sips._tcp.sip.tnx.example.com.'']> (yaml)
```

As i understand the reason is mismatch between:
https://github.com/github/octodns/blob/master/octodns/provider/route53.py#L110-L112
and
https://github.com/github/octodns/blob/master/octodns/provider/route53.py#L388-L391

Route53 provider reads regexp value as:
```
{ ...
  u'regexp': None, 
  ...
}
```

But Yaml file is written as:
```
regexp: ''
```

After replacing **'else None'** with **'else '' '**, the issue was resolved for us.

Adding tests for this case would help other providers to avoid similar issues.

Thanks!

**Comment by ross** [comment]
Thanks for the report. Will look at getting this sorted when I get a chance.

**Comment by ross** [comment]
Got a chance to look into this just now. I can verify that things are behaving sub-optimally. Fwiw, the expected way to specify no `regex` is to have:

```yaml
  regexp:
```

rather than 

```yaml
  regexp: ''
```

That would account for why `None` makes a difference. I'm going to take a look and see if there's a clean & easy way to allow `''` as well and if so I'll add it and include tests.

**Comment by ross** [comment]
Fix is in https://github.com/github/octodns/pull/163.
