### ISSUE TITLE
Domain creation does not show up in changes output

### ISSUE THREAD

**Issue by yzguy** [github/octodns#174]
One great thing OctoDNS will do is create the domain if it doesn't exist already in the provider. However right now it's a bit hidden that it does that.

I'd propose adding a `Create` stanaza in the output similar to a record creation for when it detects the domain does not exist, and that it's going to create it.

Not sure how easy it would be, a lot of the logic for this in in the individual providers

Rough example:
```
*   Create <Zone yzguy.io.> (config)
```

I figured it was worth a issue/discussion. It may not be worth adding.

**Comment by ross** [comment]
> I figured it was worth a issue/discussion. It may not be worth adding.

Yeah good call. It'd probably take a little bit of shuffling to indicate that a zone was going to be created, rather than it exists and is empty (two cases couldn't be told apart right now.) Doable and a good idea.
