### ISSUE TITLE
NS1 values for CNAME, SRV, MX, etc should be seen as absolute

### ISSUE THREAD

**Issue by yzguy** [github/octodns#179]
So I think this is worth a discussion.

I brought up to NS1 support that they allow values without the `.` and they accept/return these values in the UI/API however if you query for the record via `dig` or `nslookup`, they put the `.`. It was a while ago but they seemed not receptive to it or that it wasn't an issue.

I'm proposing we add to the OctoDNS provider for NS1 that it takes any values that should have a `.`, and adds it if it's missing. So that a value with a missing `.` is seen as equivalent to a value with the `.`

This would make it so that if the `.` was missing during a dump it doesn't error saying it's missing, and if you did something like NSOne sync to Dyn, it would see the two values as equivalent and not say that Dyn is different and want to try and recreate the records without the `.`, which results in an error as that's not allowed.

Similar functionality is [already implemented in the DNSMadeEasy provider](https://github.com/yzguy/octodns/blob/564bee93f2b71e72541c0c991a3e8124315f80a2/octodns/provider/dnsmadeeasy.py#L129-L136). Focusing around dealing with actual relative values, whereas the NS1 one would just deal with "relative" values that are known to be absolute.

Would love to hear feedback about if it's a good idea or not.

**Examples:**

If you put in `relative` as the value for a CNAME, you would expect `relative.yzguy.io.` as the answer, however if you query you get the following:

```
-> dig test.yzguy.io @dns1.p06.nsone.net +short
relative.
```

If you put `relative.yzguy.io` as the value, you would expect `relative.yzguy.io.yzguy.io.`, but you get

```
-> dig test.yzguy.io @dns1.p06.nsone.net +short
relative.yzguy.io.
```

**Comment by markmpeterson** [comment]
FYI - @yzguy thank you for the suggestion. I'll raise this with the lead engineers to discuss internally. :)

**Comment by yzguy** [comment]
@markmpeterson Do you think it's likely this would be a fix in the NS1 package or a backend change in NS1's platform itself.

I'd imagine it might be a big deal to just force all current values to have a `.` to make them absolute in the database, etc. However that would just fix it without any code changes in anyone's code for the most part.

Other part is the validation of inputs via UI/API, so that if they don't put it then it just automatically does before saving it.

**Comment by yzguy** [comment]
I think this is worth moving ahead with. It’s blocking me in some respects from using OctoDNS on a zone that has a lot of records without periods, because the input validation did not require them, and query-wise/zone transfer it gets the correct absolute value.

Should NS1 choose to fix this, it shouldn’t be a big deal in OctoDNS because we will just be checking if the value has a period or not and making the corrective action if it doesn’t. When/If NS1 changes the backend/library then they should be returning values all with periods, which means OctoDNS no longer will add another, and the functionality OctoDNS has can be removed.

I’ll look into this

**Comment by ross** [comment]
> I'm proposing we add to the OctoDNS provider for NS1 that it takes any values that should have a ., and adds it if it's missing

I'd have to dig around, but I believe there's already a provider (or two) that add missing `.` during the populate process. Since they're included in the DNS query results and essentially standard globally I think the best option is to go ahead and add it when pulling data from NS1. That should result in no diff so long as you're not changing something, but if you update it or otherwise create new records/zones it will include them.

**Comment by yzguy** [comment]
Yes, I realized it a while ago and did something similar for DnsMadeEasy: https://github.com/github/octodns/blob/master/octodns/provider/dnsmadeeasy.py#L115-L122
