### ISSUE TITLE
Any ETA for CloudFlare SRV support?

### ISSUE THREAD

**Issue by o-be-one** [github/octodns#186]
Hello folks,

just wanted to know if there is a plan to include SRV in CloudFlare provider soon? I've read in the code that it's in "todo". My usecase requires it but if it's not currently planned i'll just suspend CloudFlare in waiting for an update.

Thank you, have a good week!

**Comment by ross** [comment]
There's an existing PR being discussed with SRV support currently, https://github.com/github/octodns/pull/185. It should settle & :ship: shortly.
