### ISSUE TITLE
boto3 not installed by default

### ISSUE THREAD

**Issue by silverl** [github/octodns#228]
Should boto3 be automatically installed when running `pip install octodns`?

I tried in both Ubuntu and Windows and in each environment, my first run of octodns died due to the missing module.

After running `pip install boto3`, it ran.

**Comment by ross** [comment]
It isn't. The TL;DR is that I don't want the default install to install all of the requirements of all the providers so it doesn't install any of them. It's a doc shortcoming at the moment. The long version is over in https://github.com/github/octodns/issues/225#issuecomment-379006359. Will put a TODO list item to document this in the short term while the full solution is figured out.
