### ISSUE TITLE
Add support for Google Cloud DNS

### ISSUE THREAD

**Issue by theckman** [github/octodns#23]
Thank you for making such an awesome utility. I could definitely see this being put to good use at my organization where DNS sprawl is definitely a challenge. Unfortunately, we're using Google Cloud DNS for some zones so we wouldn't be able to apply this utility uniformly to all zones.

It seems that the Google Cloud Platform (GCP) is gaining more adoption in the industry, so I could see others needing to integrate with their DNS solution as well. Would there be any interest in having their hosted DNS supported by this utility?

**Comment by ross** [comment]
> Would there be any interest in having their hosted DNS supported by this utility?

Definitely. It's probably not something I'd get around to adding in the near-term, but PRs would be welcome. I do have a TODO item for myself to put together a doc about the best way to go about adding a new provider that would likely help. Not 100% sure when I'll get to that, hopefully soon.

**Comment by anthonysutardja** [comment]
I might be able to take this on next week as a PR

**Comment by artooro** [comment]
I'd use this as well if it supported Google Cloud DNS

**Comment by theckman** [comment]
@anthonysutardja If you have the spare time to tackle this, I'd be happy to help with a review / pairing session.

**Comment by kornface13** [comment]
I would also use the heck out of this if it supported Google CloudDNS.  :)  Thanks a ton!!!

**Comment by dolvany** [comment]
I would totally use this as well!

**Comment by yzguy** [comment]
If this was merged to master from #113 can we close this issue out?
