### ISSUE TITLE
Exception: Unknown provider class: octodns.provider.dyn.DynProvider

### ISSUE THREAD

**Issue by lczxpplnzeey** [github/octodns#230]
I know this isn't really the place to ask this, but I've followed the readme notes verbatim.

Is this something that needs to be downloaded? pip installed?

I looked in the virtualenv path and do see the providers under local/lib/python2.7/site-packages/octodns/provider/

Just puzzled why this isn't work for me.

Same situation in mac osX and ubuntu.

**Comment by yzguy** [comment]
Hello,

Yes, you will need to run `pip install dyn` to install the python package needed for that provider

**Comment by ross** [comment]
Wow. 3 of these in a week. Sorry for the trouble @lczxpplnzeey. I'll try and get the docs updated this weekend if I get a chance.

Similar to https://github.com/github/octodns/issues/228 &amp; https://github.com/github/octodns/issues/225#issuecomment-379006359

**Comment by lczxpplnzeey** [comment]
ah ok thanks!

I figured since it wasn't mention in the docs, I assumed it was automatic.
