### ISSUE TITLE
Import Functionality?

### ISSUE THREAD

**Issue by lczxpplnzeey** [github/octodns#231]
Just got this working and decided to do a test run for adding 2 A Records.

However what happened was that it wanted to delete all the records in the zone.

I did read about the warning about octodns taking over, but wasn't sure about what that entailed until I ran the command.  However I did ended up getting error about too many deletes (kudos on the warning).  It was a dry run so not too bad in either case.

Which brings up the case of populating existing entries? Is there an import function for a zone?

I tried searching the issues to see anyone had a similar issue but didn't find anything about importing records.

I can't imagine that most are starting a new zone or manually creating the entries ..

If there is a function for this, can you provide an example?

Thanks

**Comment by yzguy** [comment]
Please see: https://github.com/github/octodns#bootstrapping-config-files

You can dump the zone from the provider, then go from there

**Comment by lczxpplnzeey** [comment]
totally missed that.

Thanks.
