### ISSUE TITLE
AXFR Source

### ISSUE THREAD

**Issue by yzguy** [github/octodns#239]
So I was thinking about this today, it would be useful to be able to bootstrap your zone file from any provider in as generic of a way as possible, ie AXFR

In this case I'm thinking maybe like a Bind DNS server, etc. Something that does not have an API to call to get records.

In this way, you could get your initial zone file in OctoDNS, then that would allow you to then switch which provider you push it to, or even allow you to do a sync from Bind out to an external provider.

I know many providers allow you to import a bind compatible zone file to start your zone, so that would be one way around it, but I'm curious if there is a use case/advantage to doing it this way through OctoDNS

I'm not talking about a Zone File Provider to template out a Bind Compatible zone file though. However, maybe you could also parse a zone file into OctoDNS zone file as an alternative to a AXFR

Thoughts?

It would be interesting as you couldn't do a YAML -> the provider, but you could do Provider -> YAML

**Comment by ross** [comment]
> ... It would be interesting as you couldn't do a YAML -> the provider, but you could do Provider -> YAML

That's the idea behind `Source`s. They're able to populate zones, but not plan and apply since they're one-way.

I definitely like the idea of a AXFR `Source` though I haven't looked into the details of what it'd take to do it. I could have sworn this came up somewhere before, but there's nothing about it in the repo history so it must have been in person with someone or in chat. 

There's an existing [`Source` for TinyDNS](https://github.com/github/octodns/blob/master/octodns/source/tinydns.py) which can read it's config file and convert it to octoDNS's format. We used that as part of the internal DNS infrastructure migration. I'd imagine a similar setup for AXFR wouldn't be TOO bad to pull off.

**Comment by yzguy** [comment]
Ha, I should read more 

> An AxfrSource could be really interesting as well. Another case where a source may make sense is if you'd like to export data from a legacy service that you have no plans to push changes back into.

So internally I've written a python script that will zone transfer two providers and compare the zone results to each other and tell you what is missing, what is not matching, etc

That is using the dnspython package, which after doing the zone transfer you get basically a hash of hashes that represent all your records. That data structure would be very similar to what you get back from any provider we are already getting data from.

https://gist.github.com/yzguy/e648209d332520956ecabe6e64db24cb

**Comment by ross** [comment]
`octodns-compare` does similar comparison type stuff, though it works at the provider level, `octodns-report` does actual DNS queries against servers using octoDNS to get the list of things to check. 

```
otter:dns ross$ octodns-compare --config-file=config/production.yaml --a route53 --b dyn --zone github.com.
2018-05-03T14:07:54  [140737101296576] INFO  Manager __init__: config_file=config/production.yaml
2018-05-03T14:07:54  [140737101296576] INFO  Manager __init__:   max_workers=8
2018-05-03T14:07:54  [140737101296576] INFO  Manager __init__:   max_workers=True
2018-05-03T14:07:54  [140737101296576] INFO  Manager compare: a=['route53'], b=['dyn'], zone=github.com.
2018-05-03T14:07:55  [140737101296576] INFO  Route53Provider[route53] populate:   found 291 records, exists=True
2018-05-03T14:08:46  [140737101296576] INFO  DynProvider[dyn] populate:   found 291 records, exists=True
[Update
    <TxtRecord TXT 60, octodns-meta.github.com., ['provider=dyn']> ->
    <TxtRecord TXT 60, octodns-meta.github.com., ['provider=route53']> (route53)]
```

**Comment by yzguy** [comment]
Decent progress on this last night: https://github.com/yzguy/octodns/commit/13eece3385f32e992302da3a20f39deba8ebb405

I was able to dump my basic zone I have at home, just need to work on some of the other record types, then tests. However, it's wasn't too bad :)

Should be a cool addition for a source, and will probably add a "From Zone File" source, using dnspython it's really just a different method when you initialize the zone object.
