### ISSUE TITLE
Add support for Microsoft Azure DNS

### ISSUE THREAD

**Issue by PeterWeiler** [github/octodns#24]
Great toolset - have been looking for something like this that can automate revision-controlled configuration across multiple cloud providers

Can you please investigate supporting Azure DNS?  https://azure.microsoft.com/en-us/services/dns/

**Comment by ross** [comment]
> Can you please investigate supporting Azure DNS? https://azure.microsoft.com/en-us/services/dns/

It's probably not something I'd get around to adding in the near-term, but PRs would be welcome. I do have a TODO item for myself to put together a doc about the best way to go about adding a new provider that would likely help. Not 100% sure when I'll get to that, hopefully soon.

**Comment by h-hwang** [comment]
I am currently working on adding Azure support and should have a PR soon. For reference the fork is at https://github.com/h-hwang/octodns/tree/AZProvider

**Comment by ross** [comment]
> I am currently working on adding Azure support and should have a PR soon. For reference the fork is at https://github.com/h-hwang/octodns/tree/AZProvider

Awesome! Will take a look when it's ready.

**Comment by yzguy** [comment]
I'm assuming the [AzureProvider](https://github.com/github/octodns/blob/master/octodns/provider/azuredns.py) is the result of this.

I believe this issue can be closed.
