### ISSUE TITLE
Setting the default TTL

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#251]
I looked through the existing README and the issues, and I couldn't find it. I seem to remember octoDNS having the ability to leveraging a default TTL for all entries which do not have it explicitly set.

Can such a value be set without code hacking?

**Comment by yzguy** [comment]
Hello,

Yes you can set the Default TTL with the YamlProvider, see https://github.com/github/octodns/blob/f8a29f49d53d8d098893b427f63431aaee52fc68/octodns/provider/yaml.py#L19-L32

Currently the default is 3600 seconds, but it is configurable

**Comment by brianeclow** [comment]
Thank you! I knew I had see it, I just couldn't remember where!
