### ISSUE TITLE
Support for ANAME or Alias Records

### ISSUE THREAD

**Issue by gavinwill** [github/octodns#268]
Hi
Feature request:
It would be good if octodns could support ANAME records (described quite well here - https://blog.mythic-beasts.com/2016/10/07/aname-records/) for the providers that support ANAME Records. 

Whilst it is not officially supported by https://www.ietf.org/rfc/rfc1912.txt its usage is increasing and would be handy to be able to ensure all config is in octodns.

**Comment by ross** [comment]
`ALIAS` records are currently supported for the handful of providers that have the concept. Route53's ALIAS is a different thing and they don't support the root CNAME style ALIAS records. The [providers support matrix](https://github.com/github/octodns#supported-providers) calls out where it's supported.

**Comment by gavinwill** [comment]
I do apologise Ross. I did not intially see support in dyn for Alias but I was explicitly looking for ANAME and not alias which i can see at -  https://github.com/github/octodns/blob/master/octodns/provider/dyn.py#L207-L220

Apologies for opening this ticket and not rtfming correctly

**Comment by ross** [comment]
No need to apologize. Glad what you were after existed.
