### ISSUE TITLE
OctoDNS Report - This might not be an issue but a general information

### ISSUE THREAD

**Issue by Parushgit** [github/octodns#279]
Hi, I have setup everything with `octodns` in `route53` and now I want to see the report. I type this command `octodns-report --config-file=./config/production.yaml --zone=zone_name --source=route53` but I get `too few arguments` error. Can you tell me what arguments I am missing? Or if you can explain this report stuff with some example that will be really great. Thanks!

**Comment by ross** [comment]
If you run it without args it'll show usage:

```
(env)otter:dns ross$ octodns-report
usage: octodns-report [-h] --config-file CONFIG_FILE --zone ZONE --source
                      SOURCE [--num-workers NUM_WORKERS] [--timeout TIMEOUT]
                      [--log-stream-stdout] [--log-syslog]
                      [--syslog-device SYSLOG_DEVICE]
                      [--syslog-facility SYSLOG_FACILITY] [--debug]
                      server [server ...]
```

Looks like you might be missing the list of DNS servers to query, e.g.

```
(env)otter:octodns ross$ octodns-report --config-file=config/dev.yaml --zone githubtest.net. --source config 8.8.8.8 1.1.1.1
2018-10-24T15:35:21  [140736024888256] INFO  Manager __init__: config_file=config/dev.yaml
2018-10-24T15:35:21  [140736024888256] INFO  Manager __init__:   max_workers=4
2018-10-24T15:35:21  [140736024888256] INFO  Manager __init__:   max_workers=True
2018-10-24T15:35:21  [140736024888256] INFO  YamlProvider[config] populate:   found 22 records, exists=False
...
```

That used Google DNS (8.8.8.8) and Cloudflare (1.1.1.1) resolvers. You should be able to use any DNS server you want to test against there.

**Comment by Parushgit** [comment]
Amazing! That helped.

**Comment by Parushgit** [comment]
I was wondering one thing more. Let's say I comment out or remove one zone config in `production.yaml` file. Functionally, `octoDNS` should see it as a zone is being removed and accordingly update it in cloud provider's UI but that doesn't happen. The zone still remains there and in status it shows `no changes were planned`. Any thoughts on it?

**Comment by ross** [comment]
octoDNS doesn't know anything about or touch any zones that are unconfigured. Thus if you comment out or remove a zone's config it won't do anything. There's no way currently to get octoDNS to delete a zone. If you delete or comment all of the records in a zone it will remove all the records, but the zone will remain in place.
