### ISSUE TITLE
Command to print installed version

### ISSUE THREAD

**Issue by begincalendar** [github/octodns#290]
> (Also, I tried doing octodns-dump --version, and it would have no part of it. Think we could add a global --version flag to make checking versions easier?)

[Source](https://github.com/github/octodns/issues/284#issue-376432358)

**Comment by begincalendar** [comment]
If the presence of "--version" is supposed to override behaviour and then abort execution, I think a new `cmds/` module is needed (e.g. `octodns-version`), because of the way the command modules and CLI argument parsing is implemented (but please correct me if I'm wrong).

If the presence of "--version" doesn't have to override and abort execution (but just prints the version before execution of the command), then I guess we can make it global to all command modules.

**Comment by ross** [comment]
You're correct. It should print the version and exit. 

There's a special action in argparse that has the desired `--version` behavior, PR over in https://github.com/github/octodns/pull/291.

**Comment by begincalendar** [comment]
Didn't know about the "version" action in argparse, thanks.
