### ISSUE TITLE
DnsimpleProvider some objects with not attribute

### ISSUE THREAD

**Issue by jalogisch** [github/octodns#30]
When I try to Import Data via `DnsimpleProvider` the following AttributeError are given:

```

AttributeError: 'DnsimpleProvider' object has no attribute '_data_for_ALIAS'
AttributeError: 'DnsimpleProvider' object has no attribute '_data_for_URL'

```

The [URL](https://support.dnsimple.com/articles/url-record/) record is something specific and the ALIAS too if I understand [this document](https://support.dnsimple.com/articles/differences-between-a-cname-alias-url/) correct.

In some ways it should be possible to get the data and giving an error that some settings are not dumped and not the complete dump get revoked.

This is more a feature request to make migration more easier.

**Comment by ross** [comment]
> AttributeError: 'DnsimpleProvider' object has no attribute '_data_for_ALIAS'

`ALIAS` records aren't currently supported, but hopefully will be to the degree they can https://github.com/github/octodns/issues/26.

> AttributeError: 'DnsimpleProvider' object has no attribute '_data_for_URL'

`URL` (redirect) records aren't a supported type either.

Both are non-standard record types that vary from provider to provider (if they're available at all.) That makes them difficult to support. I'd like to get `ALIAS` support in as they're common enough, but the `URL` type might be a bit tougher. We could switch things around a bit to make unsupported types ignored by default. I have mixed feelings about that as it's a recipe for surprises when someone goes to import their zone as you're doing and some of the records are just ignored. The way it is now is a safe-than-sorry choice. Thoughts welcome.

**Comment by jalogisch** [comment]
@ross thank you for the response (and for the tool).

My general Idea was to now break and throw an error if those not supported attributes pop up. But to write the file with all other data and leave the not supported data out. 

The important is that the result need to be marked as "not ready to use" but you would be able to resolve that without looking at the GUI/Browser because you know the records that make trouble and need to be looked at. 

Currently I need to look over some domains "by hand" to identify the records and solve the issue. After that go back to the import. 

Just my 2 cent on this.

**Comment by ross** [comment]
> My general Idea was to now break and throw an error if those not supported attributes pop up. But to write the file with all other data and leave the not supported data out.

It's probably make sense to have some sort of `--ignore-unsupported` flag to do that. The way things are currently plumbed would need to change a bit to accomplish that and there'd need to be a bit of changes to the providers themselves, but it should be doable. It'd be somewhat related to the TODO task #3.

**Comment by jalogisch** [comment]
something like `--ignore-unsupported` would be awesome and should be implemented to take off the the pain if one company decide to implement something *new* ...

**Comment by ross** [comment]
`ALIAS` support is coming in https://github.com/github/octodns/issues/47. `URL` behavior will be tougher to add since it varies so much by provider. We've actually ended up implementing our own redirect service b/c of it :slightly_frowning_face:

**Comment by ross** [comment]
Forgot the other half of the reason we're doing our own `URL` style records, we wanted HTTPS and most (maybe none) of the providers support that at the moment.

**Comment by jalogisch** [comment]
thank you @ross for the update on this.
