### ISSUE TITLE
Route53 Health check: MeasureLatency necessary?

### ISSUE THREAD

**Issue by jrunkel** [github/octodns#319]
Health checks in Route 53 are created with the property 'MeasureLatency' set to true. Is that flag really necessary for the GeoDNS failover feature? I am asking that as AWS bills this as usage.

**Comment by ross** [comment]
Good question. They're not created that way intentionally, I guess it's just a default? It should be possible to create an extra option that can be added to records to enable/disable the functionality.

**Comment by jrunkel** [comment]
Ok, I did that now, have a look at #321.
