### ISSUE TITLE
Route 53: Support for Reusable Delegation Sets?

### ISSUE THREAD

**Issue by mpdude** [github/octodns#320]
Is there any way (say, like passing additional config parameters in the provider config) to make the Route 53 provider use “Reusable Delegation Sets”?

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/route-53-concepts.html#route-53-concepts-reusable-delegation-set

This makes it a lot easier to migrate a longer list of domains to Route 53 as the same set of name servers can be used for all domains.

Thanks!

**Comment by ross** [comment]
There is currently no way to do that specifically built in, but there are some thoughts/discussion of similar concepts in https://github.com/github/octodns/issues/7
