### ISSUE TITLE
Normalize records for GCP?

### ISSUE THREAD

**Issue by PeterDaveHello** [github/octodns#322]
Hello,

As GCP Cloud DNS store the alphabets in domain names and most of the records (looks like except TXT) in lower case, I wonder is it possible to normalize that before the update of comparison?

Looks like updates like below is not really meaningful, as GCP will still store them in lower case:
```
********************************************************************************
* example.com.
********************************************************************************
* gcp (GoogleCloudProvider)
*   Update
*     <MxRecord MX 60, example.com., [''1 aspmx.l.google.com.'', ''5 alt1.aspmx.l.google.com.'', ''5 alt2.aspmx.l.google.com.'', ''10 aspmx2.googlemail.com.'', ''10 aspmx3.googlemail.com.'']> ->
*     <MxRecord MX 60, example.com., [''1 ASPMX.L.GOOGLE.COM.'', ''5 ALT1.ASPMX.L.GOOGLE.COM.'', ''5 ALT2.ASPMX.L.GOOGLE.COM.'', ''10 ASPMX2.GOOGLEMAIL.COM.'', ''10 ASPMX3.GOOGLEMAIL.COM.'']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=7
```

Thanks a lot!

**Comment by ross** [comment]
Interesting. The right solution here depends on whether this is specific to GCP or could happen for other providers. In general the `Record` classes should probably normalized their values with `.lower()` (except for text style records.) A quick look and you example above seems to indicate that's not the case. `Record.name` is `.lower()`ed https://github.com/github/octodns/blob/7bf4914a41042cd283cf8cecdec88a9e37f2dbb1/octodns/record/__init__.py#L133 and it looks like `SRV` values are https://github.com/github/octodns/blob/7bf4914a41042cd283cf8cecdec88a9e37f2dbb1/octodns/record/__init__.py#L1156, but others aren't. 

The right fix here is to audit all the values and make sure they `.lower()` if they should. Shouldn't be hard too hard to do.

**Comment by PeterDaveHello** [comment]
I'd like to try sending a pull request :)

**Comment by PeterDaveHello** [comment]
PR sent here: #337 🎉

**Comment by PeterDaveHello** [comment]
Hi @ross, I just found a similar problem with CNAME record, hope you don't mind that I directly send a PR: #346, let me know if it's good enough please, thank you!
