### ISSUE TITLE
AttributeError: 'DnsMadeEasyProvider' object has no attribute '_data_for_HTTPRED'

### ISSUE THREAD

**Issue by snero** [github/octodns#327]
Hi, 

I am trying to dump/sync to our dns made easy provider and keep getting this error 

`AttributeError: 'DnsMadeEasyProvider' object has no attribute '_data_for_HTTPRED'` 

and idea on what is happening here?

**Comment by snero** [comment]
I figured this one out. It appears that HTTPRED is a particular type of DNS record that is only available dnsmadeeasy. I am thinking of mapping the call to cname instead so that it is compatible with other DNS systems

**Comment by ross** [comment]
Going to go ahead and keep this open. You are correct that the record type isn't supported by octoDNS, but the provider should generally handle that, warn about it, and skip over it rather than throw an error.

**Comment by ross** [comment]
Fixed in https://github.com/github/octodns/pull/329
