### ISSUE TITLE
domainkey in octodns-dump for route53

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#34]
Similar to #25 octodns-dump throws an error for an unescaped semicolon within a domainkey.

I pulled the top of the repository as described in the issue, and the error still persists.

**Comment by ross** [comment]
> I pulled the top of the repository as described in the issue, and the error still persists

What does `git rev-parse HEAD` show? What provider(s) are you using? Exactly the same as #25? Without more info I'm not sure what would be up.

**Comment by blakestoddard** [comment]
I'm running the version that's available in `pip` (installed today) and am hitting this with domainkey records in Route53. Exact same symptoms as #25.

**Comment by ross** [comment]
> I'm running the version that's available in pip (installed today) and am hitting this with domainkey records in Route53. Exact same symptoms as #25.

Yeah, haven't cut a new release since this bit was fixed. I have that planned on my TODO list, but was hoping to land a couple more bits before that. In the meantime you should be able to install something newer from git with a commit hash:

```
-e git+ssh://git@github.com/github/octodns.git@68fcd69f228fcfff6c8c6a970dcd40170994218e#egg=octodns
```

That just happens to be the version I have pinned in `requirements.txt` in a project. You can grab something different/newer/older by swapping out the sha.

**Comment by blakestoddard** [comment]
I believe that the change was only made for Cloudflare and hasn't been modified for Route53. 

My lack of Python knowledge isn't going to help me here. :(

**Comment by ross** [comment]
If you can drop a verbatim example of something I can drop into Route53 to exhibit the problem I can probably take a quick look at it.

**Comment by blakestoddard** [comment]
Something like this in a `TXT` record should make it pop up:
```
"v=DKIM1;p=keykeykeykeykeykeykey"
```

**Comment by ross** [comment]
Cool. Will try and take a look later today.

**Comment by brianeclow** [comment]
Thank you @blakestoddard for following up. I setup my testing environment, then I got retasked, and forgot I needed to post this.

Thank you @ross for taking a look at it. 😄

**Comment by ross** [comment]
OK. I've confirmed that Route53 does escape things for you if you haven't escaped them in your value so something similar is needed for Route53's handling of `;`. Will hopefully get a fix in place later tonight, have to go afk for now 😁

**Comment by brianeclow** [comment]
Thank you.
