### ISSUE TITLE
Allow TXT records when reading TinyDNS files

### ISSUE THREAD

**Issue by adhawkins** [github/octodns#340]
Symbiosis (https://symbiosis.bytemark.co.uk/stretch/docs/symbiosis.html) and its fork Sympl (https://sympl.host/) can generate TXT records in TinyDNS format. However, octodns does not consider a TXT record from TinyDNS as valid.

An example TXT record:

`'gentlyhosting.uk:v=spf1 +a +mx ?all:300`

The format is documented here:

https://cr.yp.to/djbdns/tinydns-data.html

It would be good to allow octodns to be able to read in (and hence sync) these TXT records from TinyDNS files

**Comment by ross** [comment]
Similar to https://github.com/github/octodns/issues/342 PRs welcome

**Comment by adhawkins** [comment]
Pretty sure this is closed as a result of PR #343
