### ISSUE TITLE
Add support for Mythic Beasts

### ISSUE THREAD

**Issue by adhawkins** [github/octodns#341]
Mythic Beasts (https://www.mythic-beasts.com/) offer DNS hosting, and provide an API to update these DNS entries (https://www.mythic-beasts.com/support/api/primary)

Would be nice to have a provider for them to allow DNS syncing using octodns

**Comment by ross** [comment]
https://github.com/ross/octodns-ddns is an example of a 3rd party provider, though different in focus. That seems like it might be a good fit for this provider and would decouple updates and releases from the main octoDNS (eventually all providers will likely move outside the core code.) I won't likely have time to look into this myself, but I'd be happy to take a look at code that does it.
