### ISSUE TITLE
Support for multiple private/public hosted zones in AWS with the same name

### ISSUE THREAD

**Issue by chathamws** [github/octodns#359]
I would like to make a feature request for octodns to support duplicate namespaces in AWS for private or public hosted zones.
Example:
I have 2 private hosted zones called example.int in AWS (assigned to 2 different VPC's). Records between the two zones are different. I would like to specify the target zone in my OctoDNS config file. The current behavior only updates the last listed zone that it pulls back from boto3. I'd like to override that behavior by explicitly defining the zone ID to update:
`targets:
  route53/ZONE_ID`

**Comment by ross** [comment]
As described in https://github.com/github/octodns/issues/260#issuecomment-417824820 this isn't a supported concept/targeted use case in octoDNS and there's no clear way to do so within the same account currently. It's concievably possible, but would require the ability to attach metadata to zone config in a way that isn't doable currently as there's no object associated with that data. It wouldn't be as simple as just adding a ZONE_ID onto the end of the targets clause as there'd be no way to get that from the config into the target provider at the point it is needed.

Closing as a dup of https://github.com/github/octodns/issues/260 as the use case is already descibed there.

**Comment by chathamws** [comment]
Wow that was quick to close... I was hoping OctoDNS could be enhanced to support our use case. I work for a very large organization and we have duplicate private namespaces within AWS VPC's for our applications to function. My thought with tacking the Zone ID onto the end of the target provider is that it would allow an override capability. When boto3 returns multiple zone files when your doing the lookup, the specified zoneID could then be used to match the correct one from that response, rather than just picking the last one in the array.
