### ISSUE TITLE
Error with SOA type for Digital Ocean provider

### ISSUE THREAD

**Issue by Its-Alex** [github/octodns#363]
When I sync Digital Ocean DNS I get this error

```
Traceback (most recent call last):
  File "/Users/alex/.local/share/virtualenvs/dns-m997HFnd/bin/octodns-dump", line 10, in <module>
    sys.exit(main())
  File "/Users/alex/.local/share/virtualenvs/dns-m997HFnd/lib/python2.7/site-packages/octodns/cmds/dump.py", line 35, in main
    *args.source)
  File "/Users/alex/.local/share/virtualenvs/dns-m997HFnd/lib/python2.7/site-packages/octodns/manager.py", line 382, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/alex/.local/share/virtualenvs/dns-m997HFnd/lib/python2.7/site-packages/octodns/provider/digitalocean.py", line 231, in populate
    data_for = getattr(self, '_data_for_{}'.format(_type))
AttributeError: 'DigitalOceanProvider' object has no attribute '_data_for_SOA'
```

After seeing code I see that it doesn't support `SOA` type but instead of just ignore it, code crash, how can we patch it ?

 Adding a check to know if attribute exist [here](https://github.com/github/octodns/blob/master/octodns/provider/digitalocean.py#L231) seems to be a good solution is it okay for you ?

**Comment by yzguy** [comment]
Hello,

You are absolutely right. It needs a couple lines to check if the record type is in the `self.SUPPORTS` set. 

This is done in the DnsMadeEasy provider here:
  https://github.com/github/octodns/blob/master/octodns/provider/dnsmadeeasy.py#L268

If you’re interested in making a PR for it that’d be great, otherwise I can.

**Comment by Its-Alex** [comment]
@yzguy This PR seems good to you ?

**Comment by jamieweb** [comment]
@ross @yzguy @Its-Alex Do you know when this fix will make it into the Python pip packaged release of OctoDNS? The Python package is currently essentially broken if you're using DigitalOcean as your provider.

**Comment by ross** [comment]
No specific plans to cut a release atm, but I'll throw it onto the todo list.

**Comment by jamieweb** [comment]
Thanks @ross, I have an article about OctoDNS on DigitalOcean ready to publish, so I'm just waiting on this bug to be fixed before I can publish it.

**Comment by ross** [comment]
Cut 0.9.6 this morning and as a side benefit the readme rendering now ALMOST works. Next release should fix the broken image. https://pypi.org/project/octodns/

**Comment by jamieweb** [comment]
@ross Thanks for sorting this so quickly!
