### ISSUE TITLE
API and LDAP

### ISSUE THREAD

**Issue by NgoJason** [github/octodns#369]
I was wondering if OctoDNS has LDAP integration and REST API support.

**Comment by ross** [comment]
> I was wondering if OctoDNS has LDAP integration and REST API support.

There's no LDAP support/integration of any shape currently and not 100% sure what you have in mind there. octoDNS itself doesn't have a REST API, but makes use of many of them in talking to various providers. octoDNS drives others things through those APIs and it wouldn't really make sense for it to have a REST API itself.
