### ISSUE TITLE
Python 3: Undefined name 'source' in manager.py

### ISSUE THREAD

**Issue by cclauss** [github/octodns#374]
In Python 3 the scoping rules change so variables created inside a list comprehension are _not_ visible in the lines that follow...

$ __flake8 .--count --show-source --statistics --select=E9,F63,F7,F82__
```
./octodns/manager.py:281:70: F821 undefined name 'source'
                                                                     source))
                                                                     ^
./octodns/manager.py:402:70: F821 undefined name 'source'
                                                                     source))
                                                                     ^
2     F821 undefined name 'source'
2
```

**Comment by ross** [comment]
That's annoying. I guess those comprehensions will need to get turned into for each appends.

**Comment by ross** [comment]
https://github.com/github/octodns/pull/384 added py3 support
