### ISSUE TITLE
Request for release of v0.9.7

### ISSUE THREAD

**Issue by danielmittelman** [github/octodns#394]
Since the release of v0.9.6 there have been many newly added providers and functionality that we're anxiously waiting for.

Is a new version expected to be released soon?

**Comment by AppleMaster** [comment]
This would be pretty handy.

**Comment by ross** [comment]
I've been ooto for a couple weeks and have a backlog of things I'm aiming to get through before cutting a release (so that they're in the release.) Will hopefully get to it end of this week or early next.
