### ISSUE TITLE
Constellix Provider: Fails to create new zone and add requested records in one run

### ISSUE THREAD

**Issue by hounster** [github/octodns#463]
If I add a new zone and records into my config, and the zone does not already exist at Constellix, my expectation would be that when I execute octodns-sync, in that run, a new zone would be created and records added as well.  What actually happens is, the new zone is indeed created, but record creation fails, raising ConstellixClientNotFound().  If I subsequently run octodns-sync immediately thereafter, with no change in my config, the records are then created with no error.  The Constellix API requires providing a zone ID typically when performing a record operation, and I believe the provider is just missing the logic to make itself aware of the zone it just created, before moving on to record creation.  I can tweak the ConstellixClient class' domains method to make this work but I don't think I'm doing it the best way.

I am using octodns version 0.9.9 and python 2.7.17

**Comment by yzguy** [comment]
I seem to remember that being expected when I created it, but it can be made better for sure. I think you're on the right path though.

I believe within ConstellixClient's `domain_create` method, after the POST, you can just have something like

```python
# Add newly created zone to domain cache
self._domains['{}.'.format(name)] = resp[0]['id']
```

**Comment by hounster** [comment]
Thank you.  I figured there was a better way.  I just tried your recommendation, the only tweak I had to make before it worked was to decode the json in the response:

`self._domains['{}.'.format(name)] = resp.json()[0]['id']`

I'll test a bit more thoroughly as well and advise.

**Comment by hounster** [comment]
I appreciate your going ahead and creating a pull request.  I did make one other change and was able to pass existing tests, but then coverage was also less than 100% subsequently.  I'm a complete novice at unittest, mock, etc... so it would have taken a bit of time for me to fix this according to standards.  I'll have a look at your pull request and maybe learn something.

**Comment by yzguy** [comment]
@hounster PR was merged, some reworking but should create zone + add all the records in the same run.

Thanks for opening the issue
