### ISSUE TITLE
Sandboxing support

### ISSUE THREAD

**Issue by johnlane** [github/octodns#488]
Hello, I'm evaluating OctoDNS and it looks good so far.

What would be useful is if providers' sandbox environments could be configured in the yaml. I was using `dnsimple` and achieved the sandbox access by modifying the Python code. But it would be nice if something like this worked:

    providers:
      dnsimple_sandbox:
        class: octodns.provider.dnsimple.DnsimpleProvider
        token: ..........
        account: 1234
        sandbox: true

**Comment by ross** [comment]
Hadn't seen DNSimple's sandbox stuff before https://developer.dnsimple.com/sandbox/. It should be possible to add a `sandbox` parameter to the provider's `__init__` function and then select the api URL to use based on that. PRs welcome.

**Comment by johnlane** [comment]
Here is a PR for optional `sandbox: true` parameter to DNSimple provider: https://github.com/github/octodns/pull/489

**Comment by johnlane** [comment]
Fantastic to see this merged so quickly, thank you.
Just wondering when the next release is due so this can be picked up by Python `pip` ?

**Comment by ross** [comment]
Don't have specific plans yet, probably a couple weeks before I get to it. In the meantime you can pip install a specific sha with something like:

```
-e git+https://git@github.com/github/octodns.git@f308f83cbe1a48770052e6a0c5efbe9531078d3f#egg=octodns
```
