### ISSUE TITLE
Escaped records are always updated

### ISSUE THREAD

**Issue by vanbroup** [github/octodns#52]
Records that are escaped by OctoDNS are updated every time you run sync (route53 and dyn, ns1 looks to be fine):

```
*     <TxtRecord TXT 1, example.com., ['\\"v=spf1 ip4:1.1.1.1/30 ip4:2.2.2.2/30 ip4:3.3.3.3/32  -all\\"']> ->
*     <TxtRecord TXT 1, example.com., ['"v=spf1 ip4:1.1.1.1/30 ip4:2.2.2.2/30 ip4:3.3.3.3/32  -all"']> (config)
```

**Comment by ross** [comment]
Can you drop a config example that results in this problem. I definitely have TXT records configured that look similar to the above that don't exhibit that problem. It may that things are configured with quotes? That'd possibly still be a bug as things shouldn't repeated change, but I'm not able to reproduce this atm.

There was a previously filed issue with a related problem with escaping in TXT records, #29, but that was around `;`.

**Comment by vanbroup** [comment]
The imported config files from Cloudflare are indeed escaped and with quotes. Let me try to re-run that export to see if it resolves the problem.

**Comment by ross** [comment]
> The imported config files from Cloudflare are indeed escaped and with quotes. Let me try to re-run that export to see if it resolves the problem.

May be an issue with the data pulled with the `CloudflareProvider`

**Comment by vanbroup** [comment]
I just confirmed that this is indeed an existing issue with the CloudflareProvider.

**Comment by ross** [comment]
> I just confirmed that this is indeed an existing issue with the CloudflareProvider.

Should be an easy fix. If you don't mind please drop a screenshot or verbatim example of what's in Cloudflare so that I can make sure I'm testing/fixing the right thing.

**Comment by vanbroup** [comment]
I found the problem, the zone I was testing with was configured the DKIM records including double quotes and escaped semicolumns, this while the Cloudflare manual states that these values should not be included or escaped. It looks like Cloudflare was correcting them automatically when publishing but the system was still holding the original records.

https://support.cloudflare.com/hc/en-us/articles/200168696-How-do-I-add-DKIM-records-

![image](https://user-images.githubusercontent.com/722070/26942598-e912c644-4c82-11e7-841e-e7cefd5f9a9b.png)

The resulted yaml config is:
```yaml
  - ttl: 1
    type: TXT
    values:
    - '"v=DKIM1\\; k=rsa\\; p=......"'
    - '"v=DKIM1\\; k=rsa\\; p=......"'
    - '"v=DKIM1\\; k=rsa\\; p=......."'
```
  
After updating the TXT records in Cloudflare, creating a new dump the sync fails on Route53 with the error **"Tried to delete resource record set [name='label._domainkey.example.com.', type='TXT'] but the rdata provided is invalid"**

```bash
2017-06-08T17:36:36  [140302525212416] INFO  Route53Provider[route53] _apply:   sending change request for batch of 143 mods, 167 ResourceRecords
2017-06-08T17:36:36  [140302525212416] DEBUG Route53Provider[route53] _really_apply:   sending change request, comment=Change: 123456789
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.8.0', 'console_scripts', 'octodns-sync')()
  File "/usr/local/lib/python2.7/dist-packages/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/usr/local/lib/python2.7/dist-packages/octodns/manager.py", line 282, in sync
    total_changes += target.apply(plan)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/base.py", line 143, in apply
    self._apply(plan)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/route53.py", line 670, in _apply
    self._really_apply(batch, zone_id)
  File "/usr/local/lib/python2.7/dist-packages/octodns/provider/route53.py", line 681, in _really_apply
    HostedZoneId=zone_id, ChangeBatch=batch)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: Tried to delete resource record set [name='label._domainkey.example.com.', type='TXT'] but the rdata provided is invalid

```

After deleting the TXT records in Route53 the sync completed successfully but it shouldn't have given an error. 

![image](https://user-images.githubusercontent.com/722070/26943218-0ee9c316-4c85-11e7-98db-14904815809a.png)

As long no double quotes are used or any escaped data the sync looks to be working fine.

**Comment by ross** [comment]
> After deleting the TXT records in Route53 the sync completed successfully but it shouldn't have given an error.

Things may have been double quoted in Route53 or something like that. I've run into the `InvalidChangeBatch` before, but only with geo dns records. I'll poke around and see if I can figure out what would get it into that state. If you have the value (quoting wise) that was in Route53 that'd be helpful.

**Comment by ross** [comment]
Some Route53 semi-colon escaping fixes in https://github.com/github/octodns/pull/60, probably not directly related to this though. The importation of records that don't pass validation already has a tracking issue, https://github.com/github/octodns/issues/8. 

Glad you were able to track it down.
