### ISSUE TITLE
Odd Continent for Timor Leste

### ISSUE THREAD

**Issue by danhanks** [github/octodns#570]
Hi, I'm looking at `octodns/record/geo_data.py` and noticing Timor Leste is the only country in the 'ID' continent (Indonesia?). I noticed this is generated from `script/generate_geo_data`, and Timor Leste (TL) is handled as an exception there, in the `continent_backups` dict. Would TL make more sense being in the 'AS' continent? (Since Indonesia itself is in AS?)

(This in the context of trying to map Octo continent codes to ultradns-specific continent codes). 

Happy to submit a PR for both `geo_data.py` and `generate_geo_data` to adjust.

**Comment by ross** [comment]
> Timor Leste (TL) is handled as an exception there, in the `continent_backups` dict. Would TL make more sense being in the 'AS' continent? (Since Indonesia itself is in AS?)

Yeah that definitely feels like an accident/type-o. @danhanks wanna do a PR to correct?

**Comment by danhanks** [comment]
PR in #571
