### ISSUE TITLE
PyPI sdist contains .pyc files

### ISSUE THREAD

**Issue by jayvdb** [github/octodns#605]
```
...
./octodns-0.9.10/tests/helpers.pyc
./octodns-0.9.10/tests/test_octodns_record.pyc
./octodns-0.9.10/tests/test_octodns_record_geo.pyc
...
```

**Comment by ross** [comment]
Odd. Not doing anything special as far as I know when that's built. Just using the standard setuptools bits.

**Comment by jayvdb** [comment]
`include` in `MANIFEST.in` shouldnt be used with directories.

**Comment by ross** [comment]
This was mostly solved by the final state/setup in https://github.com/github/octodns/pull/609. There's a single pyc file for the (empty) `octodns/__init__.py` file still in there, but that's not getting pulled in by the manifest. 

```console
(env) salmon:octodns ross$ python setup.py sdist > /dev/null && tar tvzf dist/octodns-0.9.10.tar.gz | grep pyc
-rw-r--r--  0 ross   staff     416 Nov  2 13:45 octodns-0.9.10/octodns/__init__.pyc
(env) salmon:octodns ross$
```

**Comment by ross** [comment]
This appears to be a setuptools issue based on some googling. Also worth noting that if I remove the pyc file before building the sdist it's not included:

```console
(env) salmon:octodns ross$ rm octodns/__init__.pyc
(env) salmon:octodns ross$ python setup.py sdist > /dev/null && tar tvzf dist/octodns-0.9.10.tar.gz | grep pyc
(env) salmon:octodns ross$
```

Calling this close enough.
