### ISSUE TITLE
Delete / Update Thresholds

### ISSUE THREAD

**Issue by clwells** [github/octodns#61]
What's the simplest way to alter the thresholds defined here (beyond editing the code):

https://github.com/github/octodns/blob/68fcd69f228fcfff6c8c6a970dcd40170994218e/octodns/provider/base.py#L20-L22

We're hitting them with legitimate update/deletes

**Comment by ross** [comment]
> We're hitting them with legitimate update/deletes

They're just a safety valve to warn that a lot of stuff is going to be changed. The way to acknowledge that you've looked things over and are ok with that is by adding `--force` to the command line. 

There's currently no way to configure them, but it'd probably be nice to have a way to change the values or disable them outright if you're sure/know what you're doing.

**Comment by joewilliams** [comment]
@clwells https://github.com/github/octodns/pull/120 should help by making the update and delete thresholds configurable per-provider. Give it a shot and let us know what you think!
