### ISSUE TITLE
Contributing to octoDNS

### ISSUE THREAD

**Issue by kidrahahjo** [github/octodns#611]
Hello team, I could not find any community channel like IRC / slack, so I am filing an issue.

I am new to the field of computer networking, and I want to pursue a career in this field. 
I have the theoretical knowledge of DNS and now I wanted to start contributing to repositories which handle the workflow, like octoDNS.

If possible, can someone guide me on how to get started or what technologies should I learn? I am familiar with python programming as I have contributed to a python package before.

Thank you in advance. :smile:

**Comment by yzguy** [comment]
Theoretical knowledge is good, practical is better. You can get some experience by setting up a DNS server at home (Bind9, NSD, etc.), creating a forward and reverse zone, managing records, etc. Setup a secondary server that replicates from a primary server, and ensure it can stay in sync after further record changes.

After you understand that, then the DNS providers supported by OctoDNS will be simple to work with. You could even use the AxfrSource or ZoneFileSource to take your forward/reverse zone from above and then push it up to one of the good free providers (Digitalocean, Cloudflare), could even use it to dump it to a YAML file so you can commit it to git, then keep it in source control.

Other than understanding DNS, working with DNS infrastructure, and Python the only other thing I can think of is being comfortable with APIs, usually REST APIs. You can look at a provider like DigitalOceanProvider, view the `DigitalOceanClient` code and compare it to the Digitalocean API.

Version control is a big aspect too, but clearly that's not an issue as you're on GitHub already :P

**Comment by kidrahahjo** [comment]
@yzguy Thank you for a detailed response, it really means alot. Setting up and testing a DNS server by myself seems like a great idea and will give me a good experience with the complete process.
I'm familiar with REST APIs and the DNS infrastructure. I will have a look at the different APIs provided by some providers like DigitalOceanProvider.
I'll try to dive deep into it and will get back to this thread after implementing these. 
Thanks a lot for your guidance.
