### ISSUE TITLE
DomainKey semicolon escaping

### ISSUE THREAD

**Issue by blakestoddard** [github/octodns#66]
I'm hitting an issue running `octodns-sync` (without `--do-it` FWIW) with it complaining about an unescaped semicolon when the semicolon is in-fact escaped.

Take a record that looks like this for foo.com:
```
mail._domainkey:
  ttl: 900
  type: TXT
  value: v=DKIM1\;p=iamakey
```

When attempting to use Route53 and NS1 as the providers (I didn't test others), you get this nice error message:
```
Traceback (most recent call last):
  File "<path>/dns/env/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-sync')()
  File "<path>/dns/env/src/octodns/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "<path>/dns/env/src/octodns/octodns/manager.py", line 235, in sync
    plans = [p for f in futures for p in f.result()]
  File "<path>/dns/env/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "<path>/dns/env/lib/python2.7/site-packages/concurrent/futures/_base.py", line 381, in __get_result
    raise exception_type, self._exception, self._traceback
Exception: Invalid record mail._domainkey.foo.com., unescaped ;
```

Am I doing something wrong here?

**Comment by ross** [comment]
Running the version in pypi or master of this repo? There's been a few fixes made around that since the release was cut.

**Comment by blakestoddard** [comment]
Running from the last commit in master.

**Comment by ross** [comment]
You config example looks reasonable/correct so the problem likely lies in Route53 or NS1. Without the `--doit` flag data is still pulled down from them to compare against what's configured. You might try commenting out one and then then other, or using `--target <name>` to restrict the run to one at a time to see if it happens with one or both. 

Otherwise an example of what `mail._domainkey` looks like in both places, assuming it exists, might be helpful. 

> File "<path>/dns/env/lib/python2.7/site-packages/concurrent/futures/_base.py", line 381, in __get_result
>     raise exception_type, self._exception, self._traceback
> Exception: Invalid record mail._domainkey.foo.com., unescaped ;

You also might try adding the following to the top of your main config file to avoid things being async, it may or may not help with the stacktrace. Tbh I'm not sure what's happening there to get this non-useful stacktrace. 

```yaml
manager:
  max_workers: 1
```

**Comment by blakestoddard** [comment]
Targeting each provider one-by-one doesn't replicate the issue -- everything works fine when I don't target them both. The additional `max_workers` config item didn't help either. :/

**Comment by ross** [comment]
> Targeting each provider one-by-one doesn't replicate the issue -- everything works fine when I don't target them both. The additional max_workers config item didn't help either. :/

OK. That's really weird then. If you don't mind can you drop a copy of the relevant bits of your main config file in here. If you don't want to share the details feel free to email them to me or to `s///g` things with example.com etc..

**Comment by blakestoddard** [comment]
Sure, here's what I have going on:

`config/production.yml`
```
---
providers:
  zones:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/production_zones
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY
  nsone:
    class: octodns.provider.ns1.Ns1Provider
    api_key: env/NS1_API_KEY  

zones:
  example.com.:
    sources:
      - zones
    targets:
      - route53
      - nsone
```

`config/production_zones/example.com.yaml`
```
---
? ''
: - ttl: 300
    type: A
    value: 123.456.123.456
  - ttl: 900
    type: MX
    value:
      priority: 10
      value: app-mx.example.com.
  - ttl: 900
    type: TXT
    value: v=spf1 include:_spf.example.com -all
'*':
- ttl: 600
  type: A
  value: 111.222.333.444
- ttl: 900
  type: MX
  value:
    priority: 10
    value: app-mx.example.com.
- ttl: 900
  type: TXT
  value: v=spf1 include:_spf.example.com -all
'*.staging':
- ttl: 600
  type: A
  value: 11.22.33.44
- ttl: 900
  type: MX
  value:
    priority: 10
    value: app-mx.example.com.
mail._domainkey:
  ttl: 900
  type: TXT
  value: v=DKIM1\;p=keykeykey
```

`octodns-sync --config-file=config/production.yml` output
```
(env) [ blake @ <path>/dns  (master) ] $ octodns-sync --config-file=config/production.yml
2017-06-13T15:11:55  [140736367264704] INFO  Manager __init__: config_file=config/production.yml
2017-06-13T15:11:56  [140736367264704] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False
2017-06-13T15:11:56  [140736367264704] INFO  Manager sync:   zone=example.com.
2017-06-13T15:11:56  [140736367264704] INFO  Manager sync:   sources=['zones'] -> targets=['route53', 'nsone']
2017-06-13T15:11:56  [140736367264704] INFO  YamlProvider[zones] populate:   found 20 records
2017-06-13T15:11:56  [140736367264704] INFO  Route53Provider[route53] plan: desired=example.com.
2017-06-13T15:11:56  [140736367264704] INFO  Route53Provider[route53] populate:   found 21 records
2017-06-13T15:11:56  [140736367264704] INFO  Route53Provider[route53] plan:   No changes
2017-06-13T15:11:56  [140736367264704] INFO  Ns1Provider[nsone] plan: desired=example.com.
Traceback (most recent call last):
  File "<path>/dns/env/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-sync')()
  File "<path>/dns/env/src/octodns/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "<path>/dns/env/src/octodns/octodns/manager.py", line 235, in sync
    plans = [p for f in futures for p in f.result()]
  File "<path>/dns/env/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "<path>/dns/env/lib/python2.7/site-packages/concurrent/futures/_base.py", line 381, in __get_result
    raise exception_type, self._exception, self._traceback
Exception: Invalid record mail._domainkey.example.com., unescaped ;
```

* - I chopped out a bunch of records that don't really matter since it's just extra information, hence why the "found X records" number doesn't line up with the number of records I've provided here.

**Comment by ross** [comment]
Hrm. I can't reproduce that problem. Here's the requirements.txt I used to install everything. You might try that with `virtualenv env-test && source env-test/bin/activate && pip install -r requirements.txt` and then run your sync command. This is just trying to verify what version of things is being run. 

```
PyYaml==3.12
boto3==1.4.4
botocore==1.5.4
dnspython==1.15.0
docutils==0.13.1
dyn==1.7.10
futures==3.0.5
incf.countryutils==1.0
ipaddress==1.0.18
jmespath==0.9.0
nsone==0.9.13
python-dateutil==2.6.0
requests==2.13.0
s3transfer==0.1.10
six==1.10.0
yamllint==1.6.0

-e git+ssh://git@github.com/github/octodns.git@master#egg=octodns
```

Otherwise the only changes I made were to "fix" a couple of the test ips to make them valid, `111.222.333.444` -> `111.222.222.222` etc. 

I'm using 

```
(env) sweetums:testin ross$ python --version
Python 2.7.10
``

on a mac, but I don't expect that to be matter.

**Comment by ross** [comment]
Also worth note that nothing about `example.com.` exists in Route53 or NS1 for me atm.

```
(env) sweetums:testin ross$ octodns-sync --config-file=./config/production.yaml
2017-06-13T14:25:21  [140735224197888] INFO  Manager __init__: config_file=./config/production.yaml
2017-06-13T14:25:21  [140735224197888] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False
2017-06-13T14:25:21  [140735224197888] INFO  Manager sync:   zone=example.com.
2017-06-13T14:25:21  [140735224197888] INFO  Manager sync:   sources=['zones'] -> targets=['route53', 'nsone']
2017-06-13T14:25:21  [140735224197888] INFO  YamlProvider[zones] populate:   found 9 records
2017-06-13T14:25:21  [140735224197888] INFO  Route53Provider[route53] plan: desired=example.com.
2017-06-13T14:25:22  [140735224197888] INFO  Route53Provider[route53] populate:   found 0 records
2017-06-13T14:25:22  [140735224197888] INFO  Route53Provider[route53] plan:   Creates=9, Updates=0, Deletes=0, Existing Records=0
2017-06-13T14:25:22  [140735224197888] INFO  Ns1Provider[nsone] plan: desired=example.com.
2017-06-13T14:25:24  [140735224197888] INFO  Ns1Provider[nsone] populate:   found 0 records
2017-06-13T14:25:24  [140735224197888] INFO  Ns1Provider[nsone] plan:   Creates=9, Updates=0, Deletes=0, Existing Records=0
2017-06-13T14:25:24  [140735224197888] INFO  Manager
********************************************************************************
* example.com.
********************************************************************************
* route53 (Route53Provider)
*   Create <TxtRecord TXT 900, *.example.com., ['v=spf1 include:_spf.example.com -all']> (zones)
*   Create <ARecord A 600, *.staging.example.com., ['11.22.33.44']> (zones)
*   Create <TxtRecord TXT 900, mail._domainkey.example.com., ['v=DKIM1\\;p=keykeykey']> (zones)
*   Create <TxtRecord TXT 900, example.com., ['v=spf1 include:_spf.example.com -all']> (zones)
*   Create <ARecord A 300, example.com., ['123.123.123.123']> (zones)
*   Create <ARecord A 600, *.example.com., ['111.222.222.222']> (zones)
*   Create <MxRecord MX 900, example.com., ['10 app-mx.example.com.']> (zones)
*   Create <MxRecord MX 900, *.staging.example.com., ['10 app-mx.example.com.']> (zones)
*   Create <MxRecord MX 900, *.example.com., ['10 app-mx.example.com.']> (zones)
*   Summary: Creates=9, Updates=0, Deletes=0, Existing Records=0
* nsone (Ns1Provider)
*   Create <TxtRecord TXT 900, *.example.com., ['v=spf1 include:_spf.example.com -all']> (zones)
*   Create <ARecord A 600, *.staging.example.com., ['11.22.33.44']> (zones)
*   Create <TxtRecord TXT 900, mail._domainkey.example.com., ['v=DKIM1\\;p=keykeykey']> (zones)
*   Create <TxtRecord TXT 900, example.com., ['v=spf1 include:_spf.example.com -all']> (zones)
*   Create <ARecord A 300, example.com., ['123.123.123.123']> (zones)
*   Create <ARecord A 600, *.example.com., ['111.222.222.222']> (zones)
*   Create <MxRecord MX 900, example.com., ['10 app-mx.example.com.']> (zones)
*   Create <MxRecord MX 900, *.staging.example.com., ['10 app-mx.example.com.']> (zones)
*   Create <MxRecord MX 900, *.example.com., ['10 app-mx.example.com.']> (zones)
*   Summary: Creates=9, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

**Comment by scheesman** [comment]
I am having the same issue.  I'm running the version in pypi.  If I remove the semicolons in the value, it validates fine.  But with the semicolons in, it fails with `Exception: Invalid record _dmarc.example2.net., unescaped ;`.  Here is the section of config:

```
'_dmarc':
  - type: TXT
    values:
      - "v=DMARC1; p=none; rua=mailto:test@example2.net"
```
and here is the error:
```
    raise exception_type, self._exception, self._traceback
Exception: Invalid record _dmarc.example2.net., unescaped ;
```

I also have this issue with any TXT values that include semicolons (ie `v=DKIM1; k=rsa; p=...`)

**Comment by ross** [comment]
> I am having the same issue. I'm running the version in pypi.

Version in pypi is known to have problems with escaping that have been fixed (cc https://github.com/github/octodns/issues/34 & https://github.com/github/octodns/issues/25).

Please try the octoDNS line from requirements.txt above and see if the problem persists. I plan to cut another release soon, but there's a couple small things I'm hoping to get in first. Next week is Hackweek and I plan to spend some time on octoDNS so it should happen then.

**Comment by scheesman** [comment]
Ok, so I have run it with the requirements.txt contents and did more testing.  Out of the gate, with no escaping of the semicolons, it fails with the same error.  Escaping it with double `\\` (ie. `v=DMARC1\\; p=none\\; rua=mailto:test@domain.com`) seems to work.  I didn't think to test with `\\` on the pypi version, so it might have worked.  This works on Route 53 and PowerDNS targets.  Do you know if the long-term requirement will be to escape semicolons in this manner, or is this just a workaround?

**Comment by ross** [comment]
Single `\` escapes should be sufficient. We have numerous DKIM records with them e.g.:

```yaml
foo._domainkey:
- type: TXT
  value: v=DKIM1\; h=sha256\; p=ABCDEFG...
```

**Comment by scheesman** [comment]
Here is what I get with a single `\`:

```
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "./config/seancheesman.com.yaml", line 25, column 9
found unknown escape character ';'
  in "./config/seancheesman.com.yaml", line 25, column 19
```
Relevant config section:
```
'_dmarc':
  - type: TXT
    values:
      - "v=DMARC1\; p=none\; rua=mailto:sean@seancheesman.com"
```

**Comment by scheesman** [comment]
Just tried it without wrapping the value in `"` and a single `\` worked.  I guess i assumed the value needed to be wrapped.

**Comment by ross** [comment]
> Just tried it without wrapping the value in " and a single \ worked. I guess i assumed the value needed to be wrapped.

Ah! That's a yaml quoting thing. None of our values are quoted and I'd recommend avoiding them unless you're doing things that require them. You are correct that if things are quoted with `"` yaml will turn `\\` into `\`.

`a` and `b` are equivalent here:

```yaml
foo:
  a: hello\; world
  b: "hello\\; world"
```

```
>>> s = "---\nfoo:\n  a: hello\; world\n  b: \"hello\\\\; world\""
>>> print(s)
---
foo:
  a: hello\; world
  b: "hello\\; world"
>>> d['foo']['a'] == d['foo']['b']
True
```

**Comment by scheesman** [comment]
Makes perfect sense now! Thanks!

**Comment by ross** [comment]
@blakestoddard can you confirm if you're running into the same quoted yaml problems https://github.com/github/octodns/issues/66#issuecomment-308475261? If so please close.

**Comment by blakestoddard** [comment]
Sorry about the delay here -- I've been out on vacation. It looks like our preexisting DKIM values in Route53 have unescaped semicolons, but they are already quoted. So I guess that when OctoDNS is pulling them out and parsing them via `octodns-dump` is when the semicolon is being escaped.

I was hopeful that it was the YAML quoting thing, but here are the results of my tests this morning:

```
mail._domainkey:
  ttl: 900
  type: TXT
  value: v=DKIM1\;p=keykeykey
```
results in `Exception: Invalid record mail._domainkey.foo.com., unescaped ;`

-----------------
```
mail._domainkey:
  ttl: 900
  type: TXT
  value: "v=DKIM1\;p=keykeykey"
```
results in
```
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "./config/production_zones/foo.com.yaml", line 50, column 10
found unknown escape character ';'
  in "./config/production_zones/foo.com.yaml", line 50, column 19
```

-----------------
```
mail._domainkey:
  ttl: 900
  type: TXT
  value: "v=DKIM1;p=keykeykey"
```
results in `Exception: Invalid record bcmail._domainkey.foo.com., unescaped ;`

-----------------
```
mail._domainkey:
  ttl: 900
  type: TXT
  value: "v=DKIM1\\;p=keykeykey"
```
results in `Exception: Invalid record bcmail._domainkey.foo.com., unescaped ;`

**Comment by blakestoddard** [comment]
I also did some further testing this morning with the latest from master and with `pip install -r requirements.txt` and I think this might be an NS1 issue -- it doesn't happen when I just target Route53 but it does happen if I just target NS1. I have no clue why this didn't pop up when I specified specific provider targets last time I tested this.

/cc @weyrick

**Comment by blakestoddard** [comment]
Just following up on this...

**Comment by ross** [comment]
> It looks like this might be another semicolon escaping issue? The value shown in the Route53 console is unescaped, then it is escaped by OctoDNS when it is dumped via octodns-dump. An octodns-sync run that specifically targets route53 will show that there are no changes required, but one against nsone will show the above changes as being required.

Cool. That is the expected behavior. It'll leave the Route53 record along, but if it were to change for any other reason in the future it would go ahead and escape the data sent up. Essentially it normalizes things if it's otherwise going to touch them. 

Going to call this closed, but feel free to open it back up if we run into further problems. This is definitely a confusing area. I've improved the error messages around validation in recent commits which will hopefully help a bit in the future.

**Comment by blakestoddard** [comment]
So is the double semicolon escaping thing that I showed in my last comment on this issue something that is actionable? From my knowledge, DKIM, DMARC, etc. records will not be happy with an extra backslash there. If the semicolon has already been escaped in the OctoDNS config, it should not be escaped once more, correct?

**Comment by ross** [comment]
> So is the double semicolon escaping thing that I showed in my last comment on this issue something that is actionable?

It's actually not double escaped, that's just happening due to `def __repr__`'s printing of an array of strings, [here](https://github.com/github/octodns/blob/d7b02da246800fd6149da628985a79dbb6afb3e4/octodns/record.py#L257-L259). The actual value is single quoted. At one point I planned to go in and look at manually printing the array of values to avoid that, but had forgotten. Shouldn't be too hard to do.

> From my knowledge, DKIM, DMARC, etc. records will not be happy with an extra backslash there

They won't be pushed up that way.

**Comment by blakestoddard** [comment]
Ah, awesome. That makes sense.

Thanks again!
