### ISSUE TITLE
CloudFlare issue 

### ISSUE THREAD

**Issue by jr-RXcode** [github/octodns#91]
When trying to run octodns agains cloudflare I get the following issues 
 File "/home/ec2-user/dns/env/local/lib/python2.7/site-packages/octodns/record.py", line 115, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record mydomain.com.
  - root CNAME not allowed

Any advice on how to fix ?

**Comment by jr-RXcode** [comment]
Is there a way we can skip that cname record when trying to push to cloudflare? The issue is that octodns wont let me push to cloudflare because it says it can't handle the cname. Is there a way to skip records from being push?

**Comment by ross** [comment]
There's [octodns.ignored](https://github.com/github/octodns/blob/master/octodns/record.py#L126).

```
nosync:
    type: A
    value: 1.2.3.4
    octodns:
        ignored: True
```

There's a PR that allows doing so on a provider by provider base [here](https://github.com/github/octodns/pull/111/files) that I still need to take a closer look at.

**Comment by jr-RXcode** [comment]
Looks like I can't ignore the record when i Add those setting. I get error -root CNAME not allowed. 
My zone file contains the the following entry.  
---
? ' '  
: - ttl: 1
    type: CNAME
    value: some value
    octodns:
      ignored: True

**Comment by ross** [comment]
Ah, validations are applied without ignored being taken into account. Will have to think about/dig into that a it. It's possible that `ignored` could enable `lenient` validations or it may be preferable to add a new flag, `octodns/lenient: True`, to enable it explicitly for the record. I'd probably lean towards the latter.

**Comment by ross** [comment]
After looking a bit more closely I believe the specific problem here is that the root cname needs to be of type `ALIAS` as it's supported at the root and `CNAME` is not valid.

I now think it's unrelated, but I played around with the per-record lenient config in https://github.com/github/octodns/pull/134. That may still ship.

**Comment by parkr** [comment]
@ross Hey! I'm getting octodns setup for jekyllrb.com and I am having this same issue:

```text
~/jekyll/dns$ octodns-dump --config=./config/production.yaml --output=tmp/ jekyllrb.com. cloudflare
2018-01-06T16:31:40  [140735856747328] INFO  Manager __init__: config_file=./config/production.yaml
2018-01-06T16:31:40  [140735856747328] INFO  Manager __init__:   max_workers=1
2018-01-06T16:31:40  [140735856747328] INFO  Manager __init__:   max_workers=False
2018-01-06T16:31:40  [140735856747328] INFO  Manager dump: zone=jekyllrb.com., sources=()
Traceback (most recent call last):
  File "/Users/parkr/jekyll/dns/env/bin/octodns-dump", line 11, in <module>
    sys.exit(main())
  File "/Users/parkr/jekyll/dns/env/lib/python2.7/site-packages/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/Users/parkr/jekyll/dns/env/lib/python2.7/site-packages/octodns/manager.py", line 362, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/parkr/jekyll/dns/env/lib/python2.7/site-packages/octodns/provider/cloudflare.py", line 187, in populate
    lenient=lenient)
  File "/Users/parkr/jekyll/dns/env/lib/python2.7/site-packages/octodns/record.py", line 102, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record jekyllrb.com.
  - root CNAME not allowed
```

I believe Cloudflare uses the same `ALIAS` semantics when you select `CNAME` for the root name, i.e. `CNAME` under cloudflare when `name == ''` is essentially an `ALIAS` record. When I look up the record, the results look just like an `ALIAS`. It seems like Cloudflare just doesn't follow the `ALIAS` name, but instead just refers to this functionality as `CNAME`.

```text
;; QUESTION SECTION:
;jekyllrb.com.			IN	A

;; ANSWER SECTION:
jekyllrb.com.		15	IN	A	151.101.185.147
```

Could a special case be made for this provider?

**Comment by ross** [comment]
> I believe Cloudflare uses the same ALIAS semantics when you select CNAME for the root name, i.e. CNAME under cloudflare when name == '' is essentially an ALIAS record. When I look up the record, the results look just like an ALIAS. It seems like Cloudflare just doesn't follow the ALIAS name, but instead just refers to this functionality as CNAME.

> Could a special case be made for this provider?

Yeah, if the semantics are equivalent it should be possible to translate octoDNS's `ALIAS` to their root `CNAME` under the hood as things go into and out of Cloudflare in the provider.
