### ISSUE TITLE
octodns-validate has different behavior from other commands

### ISSUE THREAD

**Issue by h-hwang** [github/octodns#95]
There is a line in octodns/cmds/validate.py that is causing different behavior when using validate vs any of the other commands. Namely line 18 of octodns/cmds/validate.py (right below) uses a default config file location:
```
parser.add_argument('--config-file', default='./config/production.yaml',
                        help='The Manager configuration file to use')
```
In contrast, the other commands use the following syntax:
```
parser.add_argument('--config-file', required=True,
                        help='The Manager configuration file to use')
```

Resulting behavior: calling the command `octodns-validate` in a directory that doesn't have a relative path to a file named `./config/production.yaml causes an IO error, whereas calling other commands such as `octodns-dump` returns a list of arguments for the command.

While this isn't breaking anything, it seems to be a little inconsistent and came up as a minor bug in testing. Is this a design choice to have this command behave in this way?

**Comment by ross** [comment]
> While this isn't breaking anything, it seems to be a little inconsistent and came up as a minor bug in testing. Is this a design choice to have this command behave in this way?

Accident/holdover from early times. Feel free to file a PR that makes it work the same as the others. There might be (relatively minor) hiccups if anyone has assumptions about the behavior (we do internally) but we're pre 1.0 and it's an easy/quick fix.

**Comment by yzguy** [comment]
#147 was merged, closing.
