### ISSUE TITLE
Allow use of https for the PowerDNS provider

### ISSUE THREAD

**Issue by poblahblahblah** [github/octodns#98]
Hello,

We would like to use https to secure the connection between octodns and powerdns, but according to https://github.com/github/octodns/blob/master/octodns/provider/powerdns.py#L34 this appears to be "hard coded" to http. Is this a change you would consider? If so, I can get a PR going for making this a configurable option, with http being the default.

**Comment by ross** [comment]
> Is this a change you would consider? If so, I can get a PR going for making this a configurable option, with http being the default.

Definitely. Should hopefully be as simple as adding an optional parameter `scheme` or something like that. Happy to take a look at a PR. Thanks.
